import { GiSandsOfTime } from "react-icons/gi";
import {
  FaBookOpen,
  FaBriefcaseMedical,
  FaCheck,
  FaClipboardList,
  FaFileInvoiceDollar,
  FaHeart,
  FaList,
  FaUser,
  FaUserTie,
} from "react-icons/fa";
import { GoHomeFill } from "react-icons/go";
import { IoIosNotifications, IoMdBriefcase } from "react-icons/io";
import { FaListCheck, FaPersonDigging } from "react-icons/fa6";
import { BsPersonBadgeFill } from "react-icons/bs";
import {
  MdCoPresent,
  MdLock,
  MdMessage,
  MdOutlinePlaylistAddCheck,
  MdPrivacyTip,
} from "react-icons/md";
import { RxLapTimer } from "react-icons/rx";
import {
  IoCheckmarkDoneCircleOutline,
  IoClipboardOutline,
} from "react-icons/io5";
import { HiMiniBuildingOffice } from "react-icons/hi2";

// Roles
export const roles = {
  1: "Staff",
  2: "Admin",
  3: "Facility",
};

// Default routes by roles
export const defaultRoutes = {
  1: "/dashboard",
  2: "/dashboard",
  3: "/dashboard",
};

export const permissions = [
  { label: "Service", key: "Service", value: "Manage Service" },
  { label: "Staff", key: "Staff", value: "Manage Staff" },
  { label: "Facility", key: "Facility", value: "Manage Facility" },
  { label: "Admin", key: "Admin", value: "Manage Admin" },
  { label: "Invoice", key: "Invoice", value: "Manage Invoice" },
];

// NavLinks
export const navLinks = {
  Admin: [
    {
      icon: <GoHomeFill className="-ml-0.5 text-xl" />,
      id: 1,
      path: "/dashboard",
      title: "dashboard",
    },
    {
      icon: <MdLock className="-ml-0.5 text-xl" />,
      id: 2,
      path: "/manage-roles",
      title: "manage_roles",
    },
    {
      icon: <FaUserTie className="-ml-0.5 text-xl" />,
      id: 3,
      path: "/manage-admin",
      title: "manage_admin",
    },
    {
      icon: <FaUser className="-ml-0.5 text-xl" />,
      id: 4,
      path: "/manage-staff",
      title: "manage_staff",
    },
    {
      icon: <HiMiniBuildingOffice className="-ml-0.5 text-xl" />,
      id: 5,
      path: "/manage-facility",
      title: "manage_facility",
    },
    {
      icon: <FaBriefcaseMedical className="text-lg" />,
      id: 6,
      path: "/service-types",
      title: "service_types",
    },
    {
      icon: <IoClipboardOutline className="text-lg" />,
      id: 7,
      path: "/invoices",
      title: "invoices",
    },
    {
      icon: <FaBookOpen className="text-lg" />,
      id: 8,
      path: "/terms-and-conditions",
      title: "terms_and_conditions",
    },
    {
      icon: <MdPrivacyTip className="text-lg" />,
      id: 9,
      path: "/privacy-policy",
      title: "privacy_policy",
    },
  ],
  Facility: [
    {
      icon: <GoHomeFill className="-ml-0.5 text-xl" />,
      id: 1,
      path: "/dashboard",
      title: "dashboard",
    },
    {
      icon: <FaListCheck className="text-lg" />,
      id: 2,
      path: "/fc-shifts",
      title: "shifts",
      items: [
        {
          title: "All",
          path: "/fc-shifts",
        },
        {
          title: "OnGoing",
          path: "/fc-shifts/on-going",
        },
        {
          title: "Completed",
          path: "/fc-shifts/completed",
        },
        {
          title: "New Shift",
          path: "/fc-shifts/new",
        },
      ],
    },
    {
      id: 3,
      icon: <IoCheckmarkDoneCircleOutline className="text-xl -ml-0.5" />,
      title: "check_in/check_out",
      path: "/check_in_outs",
    },
    {
      id: 4,
      icon: <IoClipboardOutline className="text-lg" />,
      title: "invoices",
      path: "/invoices",
    },
    {
      id: 5,
      icon: <MdMessage className="text-lg" />,
      title: "messages",
      path: "/messages",
    },
  ],
  Staff: [
    {
      icon: <GoHomeFill className="-ml-0.5 text-xl" />,
      id: 1,
      path: "/dashboard",
      title: "dashboard",
    },
    {
      icon: <FaListCheck className="text-lg" />,
      id: 2,
      path: "/shifts",
      title: "shifts",
      items: [
        {
          title: "Applied",
          path: "/shifts",
        },
        {
          title: "Completed",
          path: "/shifts/completed",
        },
      ],
    },
    {
      id: 2,
      icon: <FaList className="text-base" />,
      title: "all_jobs",
      path: "/all-jobs",
    },
    {
      id: 3,
      icon: <FaHeart className="text-base" />,
      title: "favourite_jobs",
      path: "/favourite-jobs",
    },
    {
      id: 4,
      icon: <MdMessage className="text-lg" />,
      title: "messages",
      path: "/messages",
    },
  ],
};

// Dashboard Analytics
export const dashboardCards = {
  company: [
    {
      title: "Total_Lead",
      icon: <IoMdBriefcase className="text-lg text-blue-500" />,
      colSpan: "col-span-2 sm:col-span-1",
    },
    {
      title: "Total_Task",
      icon: <FaClipboardList className="text-lg text-blue-500" />,
      colSpan: "col-span-2 sm:col-span-1",
    },
    {
      title: "Total_Invoice",
      icon: <FaFileInvoiceDollar className="text-lg text-blue-500" />,
      colSpan: "col-span-2 sm:col-span-1",
    },
    {
      title: "Total_Invoice_Paid",
      icon: (
        <div className="relative">
          <FaFileInvoiceDollar className="text-lg text-blue-500" />
          <FaCheck className="absolute text-xs p-0.5 text-blue-500 bg-white rounded-full -bottom-1 -right-1" />
        </div>
      ),
      colSpan: "col-span-2 sm:col-span-1",
    },
    {
      title: "Total_Invoice_Pending",
      icon: (
        <div className="relative">
          <FaFileInvoiceDollar className="text-lg text-blue-500" />
          <GiSandsOfTime className="absolute text-sm p-0.5 text-blue-500 bg-white rounded-full -bottom-1.5 -right-1" />
        </div>
      ),
      colSpan: "col-span-2 sm:col-span-1",
    },
    {
      title: "Total_Sales",
      icon: <BsPersonBadgeFill className="text-lg text-blue-500" />,
      colSpan: "col-span-2 sm:col-span-1",
    },
    {
      title: "Total_Workers",
      icon: <FaPersonDigging className="text-lg text-blue-500" />,
      colSpan: "col-span-2 sm:col-span-1",
    },
    {
      title: "Total_Project_Manager",
      icon: <MdCoPresent className="text-lg text-blue-500" />,
      colSpan: "col-span-2 sm:col-span-1",
    },
  ],
  project_manager: [
    {
      title: "Total_Lead",
      icon: <IoMdBriefcase className="text-lg text-blue-500" />,
      colSpan: "col-span-2",
    },
    {
      title: "Total_Task",
      icon: <FaClipboardList className="text-lg text-blue-500" />,
      colSpan: "col-span-2 sm:col-span-1",
    },
    {
      title: "Total_Task_Inprogress",
      icon: <RxLapTimer className="text-lg text-blue-500" />,
      colSpan: "col-span-2 sm:col-span-1",
    },
    {
      title: "Total_Task_Pending",
      icon: <GiSandsOfTime className="text-lg text-blue-500" />,
      colSpan: "col-span-2 sm:col-span-1",
    },
    {
      title: "Total_Task_completed",
      icon: <MdOutlinePlaylistAddCheck className="text-xl text-blue-500" />,
      colSpan: "col-span-2 sm:col-span-1",
    },
    {
      title: "Total_Sales",
      icon: <BsPersonBadgeFill className="text-lg text-blue-500" />,
      colSpan: "col-span-2 sm:col-span-1",
    },
    {
      title: "Total_Workers",
      icon: <FaPersonDigging className="text-lg text-blue-500" />,
      colSpan: "col-span-2 sm:col-span-1",
    },
  ],
};

// Countries
export const countries = [
  { value: "AF", code3: "AFG", name: "Afghanistan", number: "004" },
  { value: "AL", code3: "ALB", name: "Albania", number: "008" },
  { value: "DZ", code3: "DZA", name: "Algeria", number: "012" },
  { value: "AS", code3: "ASM", name: "American Samoa", number: "016" },
  { value: "AD", code3: "AND", name: "Andorra", number: "020" },
  { value: "AO", code3: "AGO", name: "Angola", number: "024" },
  { value: "AI", code3: "AIA", name: "Anguilla", number: "660" },
  { value: "AQ", code3: "ATA", name: "Antarctica", number: "010" },
  { value: "AG", code3: "ATG", name: "Antigua and Barbuda", number: "028" },
  { value: "AR", code3: "ARG", name: "Argentina", number: "032" },
  { value: "AM", code3: "ARM", name: "Armenia", number: "051" },
  { value: "AW", code3: "ABW", name: "Aruba", number: "533" },
  { value: "AU", code3: "AUS", name: "Australia", number: "036" },
  { value: "AT", code3: "AUT", name: "Austria", number: "040" },
  { value: "AZ", code3: "AZE", name: "Azerbaijan", number: "031" },
  { value: "BS", code3: "BHS", name: "Bahamas (the)", number: "044" },
  { value: "BH", code3: "BHR", name: "Bahrain", number: "048" },
  { value: "BD", code3: "BGD", name: "Bangladesh", number: "050" },
  { value: "BB", code3: "BRB", name: "Barbados", number: "052" },
  { value: "BY", code3: "BLR", name: "Belarus", number: "112" },
  { value: "BE", code3: "BEL", name: "Belgium", number: "056" },
  { value: "BZ", code3: "BLZ", name: "Belize", number: "084" },
  { value: "BJ", code3: "BEN", name: "Benin", number: "204" },
  { value: "BM", code3: "BMU", name: "Bermuda", number: "060" },
  { value: "BT", code3: "BTN", name: "Bhutan", number: "064" },
  {
    value: "BO",
    code3: "BOL",
    name: "Bolivia (Plurinational State of)",
    number: "068",
  },
  {
    value: "BQ",
    code3: "BES",
    name: "Bonaire, Sint Eustatius and Saba",
    number: "535",
  },
  { value: "BA", code3: "BIH", name: "Bosnia and Herzegovina", number: "070" },
  { value: "BW", code3: "BWA", name: "Botswana", number: "072" },
  { value: "BV", code3: "BVT", name: "Bouvet Island", number: "074" },
  { value: "BR", code3: "BRA", name: "Brazil", number: "076" },
  {
    value: "IO",
    code3: "IOT",
    name: "British Indian Ocean Territory (the)",
    number: "086",
  },
  { value: "BN", code3: "BRN", name: "Brunei Darussalam", number: "096" },
  { value: "BG", code3: "BGR", name: "Bulgaria", number: "100" },
  { value: "BF", code3: "BFA", name: "Burkina Faso", number: "854" },
  { value: "BI", code3: "BDI", name: "Burundi", number: "108" },
  { value: "CV", code3: "CPV", name: "Cabo Verde", number: "132" },
  { value: "KH", code3: "KHM", name: "Cambodia", number: "116" },
  { value: "CM", code3: "CMR", name: "Cameroon", number: "120" },
  { value: "CA", code3: "CAN", name: "Canada", number: "124" },
  { value: "KY", code3: "CYM", name: "Cayman Islands (the)", number: "136" },
  {
    value: "CF",
    code3: "CAF",
    name: "Central African Republic (the)",
    number: "140",
  },
  { value: "TD", code3: "TCD", name: "Chad", number: "148" },
  { value: "CL", code3: "CHL", name: "Chile", number: "152" },
  { value: "CN", code3: "CHN", name: "China", number: "156" },
  { value: "CX", code3: "CXR", name: "Christmas Island", number: "162" },
  {
    value: "CC",
    code3: "CCK",
    name: "Cocos (Keeling) Islands (the)",
    number: "166",
  },
  { value: "CO", code3: "COL", name: "Colombia", number: "170" },
  { value: "KM", code3: "COM", name: "Comoros (the)", number: "174" },
  {
    value: "CD",
    code3: "COD",
    name: "Congo (the Democratic Republic of the)",
    number: "180",
  },
  { value: "CG", code3: "COG", name: "Congo (the)", number: "178" },
  { value: "CK", code3: "COK", name: "Cook Islands (the)", number: "184" },
  { value: "CR", code3: "CRI", name: "Costa Rica", number: "188" },
  { value: "HR", code3: "HRV", name: "Croatia", number: "191" },
  { value: "CU", code3: "CUB", name: "Cuba", number: "192" },
  { value: "CW", code3: "CUW", name: "Curaçao", number: "531" },
  { value: "CY", code3: "CYP", name: "Cyprus", number: "196" },
  { value: "CZ", code3: "CZE", name: "Czechia", number: "203" },
  { value: "CI", code3: "CIV", name: "Côte d'Ivoire", number: "384" },
  { value: "DK", code3: "DNK", name: "Denmark", number: "208" },
  { value: "DJ", code3: "DJI", name: "Djibouti", number: "262" },
  { value: "DM", code3: "DMA", name: "Dominica", number: "212" },
  {
    value: "DO",
    code3: "DOM",
    name: "Dominican Republic (the)",
    number: "214",
  },
  { value: "EC", code3: "ECU", name: "Ecuador", number: "218" },
  { value: "EG", code3: "EGY", name: "Egypt", number: "818" },
  { value: "SV", code3: "SLV", name: "El Salvador", number: "222" },
  { value: "GQ", code3: "GNQ", name: "Equatorial Guinea", number: "226" },
  { value: "ER", code3: "ERI", name: "Eritrea", number: "232" },
  { value: "EE", code3: "EST", name: "Estonia", number: "233" },
  { value: "SZ", code3: "SWZ", name: "Eswatini", number: "748" },
  { value: "ET", code3: "ETH", name: "Ethiopia", number: "231" },
  {
    value: "FK",
    code3: "FLK",
    name: "Falkland Islands (the) [Malvinas]",
    number: "238",
  },
  { value: "FO", code3: "FRO", name: "Faroe Islands (the)", number: "234" },
  { value: "FJ", code3: "FJI", name: "Fiji", number: "242" },
  { value: "FI", code3: "FIN", name: "Finland", number: "246" },
  { value: "FR", code3: "FRA", name: "France", number: "250" },
  { value: "GF", code3: "GUF", name: "French Guiana", number: "254" },
  { value: "PF", code3: "PYF", name: "French Polynesia", number: "258" },
  {
    value: "TF",
    code3: "ATF",
    name: "French Southern Territories (the)",
    number: "260",
  },
  { value: "GA", code3: "GAB", name: "Gabon", number: "266" },
  { value: "GM", code3: "GMB", name: "Gambia (the)", number: "270" },
  { value: "GE", code3: "GEO", name: "Georgia", number: "268" },
  { value: "DE", code3: "DEU", name: "Germany", number: "276" },
  { value: "GH", code3: "GHA", name: "Ghana", number: "288" },
  { value: "GI", code3: "GIB", name: "Gibraltar", number: "292" },
  { value: "GR", code3: "GRC", name: "Greece", number: "300" },
  { value: "GL", code3: "GRL", name: "Greenland", number: "304" },
  { value: "GD", code3: "GRD", name: "Grenada", number: "308" },
  { value: "GP", code3: "GLP", name: "Guadeloupe", number: "312" },
  { value: "GU", code3: "GUM", name: "Guam", number: "316" },
  { value: "GT", code3: "GTM", name: "Guatemala", number: "320" },
  { value: "GG", code3: "GGY", name: "Guernsey", number: "831" },
  { value: "GN", code3: "GIN", name: "Guinea", number: "324" },
  { value: "GW", code3: "GNB", name: "Guinea-Bissau", number: "624" },
  { value: "GY", code3: "GUY", name: "Guyana", number: "328" },
  { value: "HT", code3: "HTI", name: "Haiti", number: "332" },
  {
    value: "HM",
    code3: "HMD",
    name: "Heard Island and McDonald Islands",
    number: "334",
  },
  { value: "VA", code3: "VAT", name: "Holy See (the)", number: "336" },
  { value: "HN", code3: "HND", name: "Honduras", number: "340" },
  { value: "HK", code3: "HKG", name: "Hong Kong", number: "344" },
  { value: "HU", code3: "HUN", name: "Hungary", number: "348" },
  { value: "IS", code3: "ISL", name: "Iceland", number: "352" },
  { value: "IN", code3: "IND", name: "India", number: "356" },
  { value: "ID", code3: "IDN", name: "Indonesia", number: "360" },
  {
    value: "IR",
    code3: "IRN",
    name: "Iran (Islamic Republic of)",
    number: "364",
  },
  { value: "IQ", code3: "IRQ", name: "Iraq", number: "368" },
  { value: "IE", code3: "IRL", name: "Ireland", number: "372" },
  { value: "IM", code3: "IMN", name: "Isle of Man", number: "833" },
  { value: "IL", code3: "ISR", name: "Israel", number: "376" },
  { value: "IT", code3: "ITA", name: "Italy", number: "380" },
  { value: "JM", code3: "JAM", name: "Jamaica", number: "388" },
  { value: "JP", code3: "JPN", name: "Japan", number: "392" },
  { value: "JE", code3: "JEY", name: "Jersey", number: "832" },
  { value: "JO", code3: "JOR", name: "Jordan", number: "400" },
  { value: "KZ", code3: "KAZ", name: "Kazakhstan", number: "398" },
  { value: "KE", code3: "KEN", name: "Kenya", number: "404" },
  { value: "KI", code3: "KIR", name: "Kiribati", number: "296" },
  {
    value: "KP",
    code3: "PRK",
    name: "Korea (the Democratic People's Republic of)",
    number: "408",
  },
  { value: "KR", code3: "KOR", name: "Korea (the Republic of)", number: "410" },
  { value: "KW", code3: "KWT", name: "Kuwait", number: "414" },
  { value: "KG", code3: "KGZ", name: "Kyrgyzstan", number: "417" },
  {
    value: "LA",
    code3: "LAO",
    name: "Lao People's Democratic Republic (the)",
    number: "418",
  },
  { value: "LV", code3: "LVA", name: "Latvia", number: "428" },
  { value: "LB", code3: "LBN", name: "Lebanon", number: "422" },
  { value: "LS", code3: "LSO", name: "Lesotho", number: "426" },
  { value: "LR", code3: "LBR", name: "Liberia", number: "430" },
  { value: "LY", code3: "LBY", name: "Libya", number: "434" },
  { value: "LI", code3: "LIE", name: "Liechtenstein", number: "438" },
  { value: "LT", code3: "LTU", name: "Lithuania", number: "440" },
  { value: "LU", code3: "LUX", name: "Luxembourg", number: "442" },
  { value: "MO", code3: "MAC", name: "Macao", number: "446" },
  { value: "MG", code3: "MDG", name: "Madagascar", number: "450" },
  { value: "MW", code3: "MWI", name: "Malawi", number: "454" },
  { value: "MY", code3: "MYS", name: "Malaysia", number: "458" },
  { value: "MV", code3: "MDV", name: "Maldives", number: "462" },
  { value: "ML", code3: "MLI", name: "Mali", number: "466" },
  { value: "MT", code3: "MLT", name: "Malta", number: "470" },
  { value: "MH", code3: "MHL", name: "Marshall Islands (the)", number: "584" },
  { value: "MQ", code3: "MTQ", name: "Martinique", number: "474" },
  { value: "MR", code3: "MRT", name: "Mauritania", number: "478" },
  { value: "MU", code3: "MUS", name: "Mauritius", number: "480" },
  { value: "YT", code3: "MYT", name: "Mayotte", number: "175" },
  { value: "MX", code3: "MEX", name: "Mexico", number: "484" },
  {
    value: "FM",
    code3: "FSM",
    name: "Micronesia (Federated States of)",
    number: "583",
  },
  {
    value: "MD",
    code3: "MDA",
    name: "Moldova (the Republic of)",
    number: "498",
  },
  { value: "MC", code3: "MCO", name: "Monaco", number: "492" },
  { value: "MN", code3: "MNG", name: "Mongolia", number: "496" },
  { value: "ME", code3: "MNE", name: "Montenegro", number: "499" },
  { value: "MS", code3: "MSR", name: "Montserrat", number: "500" },
  { value: "MA", code3: "MAR", name: "Morocco", number: "504" },
  { value: "MZ", code3: "MOZ", name: "Mozambique", number: "508" },
  { value: "MM", code3: "MMR", name: "Myanmar", number: "104" },
  { value: "NA", code3: "NAM", name: "Namibia", number: "516" },
  { value: "NR", code3: "NRU", name: "Nauru", number: "520" },
  { value: "NP", code3: "NPL", name: "Nepal", number: "524" },
  { value: "NL", code3: "NLD", name: "Netherlands (the)", number: "528" },
  { value: "NC", code3: "NCL", name: "New Caledonia", number: "540" },
  { value: "NZ", code3: "NZL", name: "New Zealand", number: "554" },
  { value: "NI", code3: "NIC", name: "Nicaragua", number: "558" },
  { value: "NE", code3: "NER", name: "Niger (the)", number: "562" },
  { value: "NG", code3: "NGA", name: "Nigeria", number: "566" },
  { value: "NU", code3: "NIU", name: "Niue", number: "570" },
  { value: "NF", code3: "NFK", name: "Norfolk Island", number: "574" },
  {
    value: "MP",
    code3: "MNP",
    name: "Northern Mariana Islands (the)",
    number: "580",
  },
  { value: "NO", code3: "NOR", name: "Norway", number: "578" },
  { value: "OM", code3: "OMN", name: "Oman", number: "512" },
  { value: "PK", code3: "PAK", name: "Pakistan", number: "586" },
  { value: "PW", code3: "PLW", name: "Palau", number: "585" },
  { value: "PS", code3: "PSE", name: "Palestine, State of", number: "275" },
  { value: "PA", code3: "PAN", name: "Panama", number: "591" },
  { value: "PG", code3: "PNG", name: "Papua New Guinea", number: "598" },
  { value: "PY", code3: "PRY", name: "Paraguay", number: "600" },
  { value: "PE", code3: "PER", name: "Peru", number: "604" },
  { value: "PH", code3: "PHL", name: "Philippines (the)", number: "608" },
  { value: "PN", code3: "PCN", name: "Pitcairn", number: "612" },
  { value: "PL", code3: "POL", name: "Poland", number: "616" },
  { value: "PT", code3: "PRT", name: "Portugal", number: "620" },
  { value: "PR", code3: "PRI", name: "Puerto Rico", number: "630" },
  { value: "QA", code3: "QAT", name: "Qatar", number: "634" },
  {
    value: "MK",
    code3: "MKD",
    name: "Republic of North Macedonia",
    number: "807",
  },
  { value: "RO", code3: "ROU", name: "Romania", number: "642" },
  {
    value: "RU",
    code3: "RUS",
    name: "Russian Federation (the)",
    number: "643",
  },
  { value: "RW", code3: "RWA", name: "Rwanda", number: "646" },
  { value: "RE", code3: "REU", name: "Réunion", number: "638" },
  { value: "BL", code3: "BLM", name: "Saint Barthélemy", number: "652" },
  {
    value: "SH",
    code3: "SHN",
    name: "Saint Helena, Ascension and Tristan da Cunha",
    number: "654",
  },
  { value: "KN", code3: "KNA", name: "Saint Kitts and Nevis", number: "659" },
  { value: "LC", code3: "LCA", name: "Saint Lucia", number: "662" },
  {
    value: "MF",
    code3: "MAF",
    name: "Saint Martin (French part)",
    number: "663",
  },
  {
    value: "PM",
    code3: "SPM",
    name: "Saint Pierre and Miquelon",
    number: "666",
  },
  {
    value: "VC",
    code3: "VCT",
    name: "Saint Vincent and the Grenadines",
    number: "670",
  },
  { value: "WS", code3: "WSM", name: "Samoa", number: "882" },
  { value: "SM", code3: "SMR", name: "San Marino", number: "674" },
  { value: "ST", code3: "STP", name: "Sao Tome and Principe", number: "678" },
  { value: "SA", code3: "SAU", name: "Saudi Arabia", number: "682" },
  { value: "SN", code3: "SEN", name: "Senegal", number: "686" },
  { value: "RS", code3: "SRB", name: "Serbia", number: "688" },
  { value: "SC", code3: "SYC", name: "Seychelles", number: "690" },
  { value: "SL", code3: "SLE", name: "Sierra Leone", number: "694" },
  { value: "SG", code3: "SGP", name: "Singapore", number: "702" },
  {
    value: "SX",
    code3: "SXM",
    name: "Sint Maarten (Dutch part)",
    number: "534",
  },
  { value: "SK", code3: "SVK", name: "Slovakia", number: "703" },
  { value: "SI", code3: "SVN", name: "Slovenia", number: "705" },
  { value: "SB", code3: "SLB", name: "Solomon Islands", number: "090" },
  { value: "SO", code3: "SOM", name: "Somalia", number: "706" },
  { value: "ZA", code3: "ZAF", name: "South Africa", number: "710" },
  {
    value: "GS",
    code3: "SGS",
    name: "South Georgia and the South Sandwich Islands",
    number: "239",
  },
  { value: "SS", code3: "SSD", name: "South Sudan", number: "728" },
  { value: "ES", code3: "ESP", name: "Spain", number: "724" },
  { value: "LK", code3: "LKA", name: "Sri Lanka", number: "144" },
  { value: "SD", code3: "SDN", name: "Sudan (the)", number: "729" },
  { value: "SR", code3: "SUR", name: "Suriname", number: "740" },
  { value: "SJ", code3: "SJM", name: "Svalbard and Jan Mayen", number: "744" },
  { value: "SE", code3: "SWE", name: "Sweden", number: "752" },
  { value: "CH", code3: "CHE", name: "Switzerland", number: "756" },
  { value: "SY", code3: "SYR", name: "Syrian Arab Republic", number: "760" },
  { value: "TW", code3: "TWN", name: "Taiwan", number: "158" },
  { value: "TJ", code3: "TJK", name: "Tajikistan", number: "762" },
  {
    value: "TZ",
    code3: "TZA",
    name: "Tanzania, United Republic of",
    number: "834",
  },
  { value: "TH", code3: "THA", name: "Thailand", number: "764" },
  { value: "TL", code3: "TLS", name: "Timor-Leste", number: "626" },
  { value: "TG", code3: "TGO", name: "Togo", number: "768" },
  { value: "TK", code3: "TKL", name: "Tokelau", number: "772" },
  { value: "TO", code3: "TON", name: "Tonga", number: "776" },
  { value: "TT", code3: "TTO", name: "Trinidad and Tobago", number: "780" },
  { value: "TN", code3: "TUN", name: "Tunisia", number: "788" },
  { value: "TR", code3: "TUR", name: "Turkey", number: "792" },
  { value: "TM", code3: "TKM", name: "Turkmenistan", number: "795" },
  {
    value: "TC",
    code3: "TCA",
    name: "Turks and Caicos Islands (the)",
    number: "796",
  },
  { value: "TV", code3: "TUV", name: "Tuvalu", number: "798" },
  { value: "UG", code3: "UGA", name: "Uganda", number: "800" },
  { value: "UA", code3: "UKR", name: "Ukraine", number: "804" },
  {
    value: "AE",
    code3: "ARE",
    name: "United Arab Emirates (the)",
    number: "784",
  },
  {
    value: "GB",
    code3: "GBR",
    name: "United Kingdom of Great Britain and Northern Ireland (the)",
    number: "826",
  },
  {
    value: "UM",
    code3: "UMI",
    name: "United States Minor Outlying Islands (the)",
    number: "581",
  },
  {
    value: "US",
    code3: "USA",
    name: "United States of America (the)",
    number: "840",
  },
  { value: "UY", code3: "URY", name: "Uruguay", number: "858" },
  { value: "UZ", code3: "UZB", name: "Uzbekistan", number: "860" },
  { value: "VU", code3: "VUT", name: "Vanuatu", number: "548" },
  {
    value: "VE",
    code3: "VEN",
    name: "Venezuela (Bolivarian Republic of)",
    number: "862",
  },
  { value: "VN", code3: "VNM", name: "Viet Nam", number: "704" },
  {
    value: "VG",
    code3: "VGB",
    name: "Virgin Islands (British)",
    number: "092",
  },
  { value: "VI", code3: "VIR", name: "Virgin Islands (U.S.)", number: "850" },
  { value: "WF", code3: "WLF", name: "Wallis and Futuna", number: "876" },
  { value: "EH", code3: "ESH", name: "Western Sahara", number: "732" },
  { value: "YE", code3: "YEM", name: "Yemen", number: "887" },
  { value: "ZM", code3: "ZMB", name: "Zambia", number: "894" },
  { value: "ZW", code3: "ZWE", name: "Zimbabwe", number: "716" },
  { value: "AX", code3: "ALA", name: "Åland Islands", number: "248" },
];

// Country States
export const states = {
  Afghanistan: [
    "Badakhshan",
    "Badghis",
    "Baghlan",
    "Balkh",
    "Bamian",
    "Daykondi",
    "Farah",
    "Faryab",
    "Ghazni",
    "Ghowr",
    "Helmand",
    "Herat",
    "Jowzjan",
    "Kabul",
    "Kandahar",
    "Kapisa",
    "Khost",
    "Konar",
    "Kondoz",
    "Laghman",
    "Lowgar",
    "Nangarhar",
    "Nimruz",
    "Nurestan",
    "Oruzgan",
    "Paktia",
    "Paktika",
    "Panjshir",
    "Parvan",
    "Samangan",
    "Sar-e Pol",
    "Takhar",
    "Vardak",
    "Zabol",
  ],
  Albania: [
    "Berat",
    "Dibres",
    "Durres",
    "Elbasan",
    "Fier",
    "Gjirokastre",
    "Korce",
    "Kukes",
    "Lezhe",
    "Shkoder",
    "Tirane",
    "Vlore",
  ],
  Algeria: [
    "Adrar",
    "Ain Defla",
    "Ain Temouchent",
    "Alger",
    "Annaba",
    "Batna",
    "Bechar",
    "Bejaia",
    "Biskra",
    "Blida",
    "Bordj Bou Arreridj",
    "Bouira",
    "Boumerdes",
    "Chlef",
    "Constantine",
    "Djelfa",
    "El Bayadh",
    "El Oued",
    "El Tarf",
    "Ghardaia",
    "Guelma",
    "Illizi",
    "Jijel",
    "Khenchela",
    "Laghouat",
    "Muaskar",
    "Medea",
    "Mila",
    "Mostaganem",
    "M'Sila",
    "Naama",
    "Oran",
    "Ouargla",
    "Oum el Bouaghi",
    "Relizane",
    "Saida",
    "Setif",
    "Sidi Bel Abbes",
    "Skikda",
    "Souk Ahras",
    "Tamanghasset",
    "Tebessa",
    "Tiaret",
    "Tindouf",
    "Tipaza",
    "Tissemsilt",
    "Tizi Ouzou",
    "Tlemcen",
  ],
  "American Samoa": null,
  Andorra: [
    "Andorra la Vella",
    "Canillo",
    "Encamp",
    "Escaldes-Engordany",
    "La Massana",
    "Ordino",
    "Sant Julia de Loria",
  ],
  Angola: [
    "Bengo",
    "Benguela",
    "Bie",
    "Cabinda",
    "Cuando Cubango",
    "Cuanza Norte",
    "Cuanza Sul",
    "Cunene",
    "Huambo",
    "Huila",
    "Luanda",
    "Lunda Norte",
    "Lunda Sul",
    "Malanje",
    "Moxico",
    "Namibe",
    "Uige",
    "Zaire",
  ],
  Anguilla: null,
  Antarctica: null,
  "Antigua and Barbuda": [
    "Barbuda",
    "Redonda",
    "Saint George",
    "Saint John",
    "Saint Mary",
    "Saint Paul",
    "Saint Peter",
    "Saint Philip",
  ],
  Argentina: [
    "Buenos Aires",
    "Buenos Aires Capital",
    "Catamarca",
    "Chaco",
    "Chubut",
    "Cordoba",
    "Corrientes",
    "Entre Rios",
    "Formosa",
    "Jujuy",
    "La Pampa",
    "La Rioja",
    "Mendoza",
    "Misiones",
    "Neuquen",
    "Rio Negro",
    "Salta",
    "San Juan",
    "San Luis",
    "Santa Cruz",
    "Santa Fe",
    "Santiago del Estero",
    "Tierra del Fuego",
    "Tucuman",
  ],
  Armenia: [
    "Aragatsotn",
    "Ararat",
    "Armavir",
    "Geghark'unik'",
    "Kotayk'",
    "Lorri",
    "Shirak",
    "Syunik'",
    "Tavush",
    "Vayots' Dzor",
    "Yerevan",
  ],
  Aruba: null,
  Australia: [
    "Australian Capital Territory",
    "New South Wales",
    "Northern Territory",
    "Queensland",
    "South Australia",
    "Tasmania",
    "Victoria",
    "Western Australia",
  ],
  Austria: [
    "Burgenland",
    "Kaernten",
    "Niederoesterreich",
    "Oberoesterreich",
    "Salzburg",
    "Steiermark",
    "Tirol",
    "Vorarlberg",
    "Wien",
  ],
  Azerbaijan: [
    "Abseron Rayonu",
    "Agcabadi Rayonu",
    "Agdam Rayonu",
    "Agdas Rayonu",
    "Agstafa Rayonu",
    "Agsu Rayonu",
    "Astara Rayonu",
    "Balakan Rayonu",
    "Barda Rayonu",
    "Beylaqan Rayonu",
    "Bilasuvar Rayonu",
    "Cabrayil Rayonu",
    "Calilabad Rayonu",
    "Daskasan Rayonu",
    "Davaci Rayonu",
    "Fuzuli Rayonu",
    "Gadabay Rayonu",
    "Goranboy Rayonu",
    "Goycay Rayonu",
    "Haciqabul Rayonu",
    "Imisli Rayonu",
    "Ismayilli Rayonu",
    "Kalbacar Rayonu",
    "Kurdamir Rayonu",
    "Lacin Rayonu",
    "Lankaran Rayonu",
    "Lerik Rayonu",
    "Masalli Rayonu",
    "Neftcala Rayonu",
    "Oguz Rayonu",
    "Qabala Rayonu",
    "Qax Rayonu",
    "Qazax Rayonu",
    "Qobustan Rayonu",
    "Quba Rayonu",
    "Qubadli Rayonu",
    "Qusar Rayonu",
    "Saatli Rayonu",
    "Sabirabad Rayonu",
    "Saki Rayonu",
    "Salyan Rayonu",
    "Samaxi Rayonu",
    "Samkir Rayonu",
    "Samux Rayonu",
    "Siyazan Rayonu",
    "Susa Rayonu",
    "Tartar Rayonu",
    "Tovuz Rayonu",
    "Ucar Rayonu",
    "Xacmaz Rayonu",
    "Xanlar Rayonu",
    "Xizi Rayonu",
    "Xocali Rayonu",
    "Xocavand Rayonu",
    "Yardimli Rayonu",
    "Yevlax Rayonu",
    "Zangilan Rayonu",
    "Zaqatala Rayonu",
    "Zardab Rayonu",
    "Ali Bayramli Sahari",
    "Baki Sahari",
    "Ganca Sahari",
    "Lankaran Sahari",
    "Mingacevir Sahari",
    "Naftalan Sahari",
    "Saki Sahari",
    "Sumqayit Sahari",
    "Susa Sahari",
    "Xankandi Sahari",
    "Yevlax Sahari",
    "Naxcivan Muxtar",
  ],
  "Bahamas (the)": [
    "Acklins and Crooked Islands",
    "Bimini",
    "Cat Island",
    "Exuma",
    "Freeport",
    "Fresh Creek",
    "Governor's Harbour",
    "Green Turtle Cay",
    "Harbour Island",
    "High Rock",
    "Inagua",
    "Kemps Bay",
    "Long Island",
    "Marsh Harbour",
    "Mayaguana",
    "New Providence",
    "Nichollstown and Berry Islands",
    "Ragged Island",
    "Rock Sound",
    "Sandy Point",
    "San Salvador and Rum Cay",
  ],
  Bahrain: [
    "Al Hadd",
    "Al Manamah",
    "Al Mintaqah al Gharbiyah",
    "Al Mintaqah al Wusta",
    "Al Mintaqah ash Shamaliyah",
    "Al Muharraq",
    "Ar Rifa' wa al Mintaqah al Janubiyah",
    "Jidd Hafs",
    "Madinat Hamad",
    "Madinat 'Isa",
    "Juzur Hawar",
    "Sitrah",
  ],
  Bangladesh: [
    "Barisal",
    "Chittagong",
    "Dhaka",
    "Khulna",
    "Rajshahi",
    "Sylhet",
  ],
  Barbados: [
    "Christ Church",
    "Saint Andrew",
    "Saint George",
    "Saint James",
    "Saint John",
    "Saint Joseph",
    "Saint Lucy",
    "Saint Michael",
    "Saint Peter",
    "Saint Philip",
    "Saint Thomas",
  ],
  Belarus: [
    "Brest",
    "Homyel",
    "Horad Minsk",
    "Hrodna",
    "Mahilyow",
    "Minsk",
    "Vitsyebsk",
  ],
  Belgium: [
    "Antwerpen",
    "Brabant Wallon",
    "Brussels",
    "Flanders",
    "Hainaut",
    "Liege",
    "Limburg",
    "Luxembourg",
    "Namur",
    "Oost-Vlaanderen",
    "Vlaams-Brabant",
    "Wallonia",
    "West-Vlaanderen",
  ],
  Belize: ["Belize", "Cayo", "Corozal", "Orange Walk", "Stann Creek", "Toledo"],
  Benin: [
    "Alibori",
    "Atakora",
    "Atlantique",
    "Borgou",
    "Collines",
    "Donga",
    "Kouffo",
    "Littoral",
    "Mono",
    "Oueme",
    "Plateau",
    "Zou",
  ],
  Bermuda: [
    "Devonshire",
    "Hamilton",
    "Hamilton",
    "Paget",
    "Pembroke",
    "Saint George",
    "Saint George's",
    "Sandys",
    "Smith's",
    "Southampton",
    "Warwick",
  ],
  Bhutan: [
    "Bumthang",
    "Chukha",
    "Dagana",
    "Gasa",
    "Haa",
    "Lhuntse",
    "Mongar",
    "Paro",
    "Pemagatshel",
    "Punakha",
    "Samdrup Jongkhar",
    "Samtse",
    "Sarpang",
    "Thimphu",
    "Trashigang",
    "Trashiyangste",
    "Trongsa",
    "Tsirang",
    "Wangdue Phodrang",
    "Zhemgang",
  ],
  "Bolivia (Plurinational State of)": [
    "Chuquisaca",
    "Cochabamba",
    "Beni",
    "La Paz",
    "Oruro",
    "Pando",
    "Potosi",
    "Santa Cruz",
    "Tarija",
  ],
  "Bonaire, Sint Eustatius and Saba": null,
  "Bosnia and Herzegovina": [
    "Una-Sana [Federation]",
    "Posavina [Federation]",
    "Tuzla [Federation]",
    "Zenica-Doboj [Federation]",
    "Bosnian Podrinje [Federation]",
    "Central Bosnia [Federation]",
    "Herzegovina-Neretva [Federation]",
    "West Herzegovina [Federation]",
    "Sarajevo [Federation]",
    " West Bosnia [Federation]",
    "Banja Luka [RS]",
    "Bijeljina [RS]",
    "Doboj [RS]",
    "Fo?a [RS]",
    "Sarajevo-Romanija [RS]",
    "Trebinje [RS]",
    "Vlasenica [RS]",
  ],
  Botswana: [
    "Central",
    "Ghanzi",
    "Kgalagadi",
    "Kgatleng",
    "Kweneng",
    "North East",
    "North West",
    "South East",
    "Southern",
  ],
  "Bouvet Island": null,
  Brazil: [
    "Acre",
    "Alagoas",
    "Amapa",
    "Amazonas",
    "Bahia",
    "Ceara",
    "Distrito Federal",
    "Espirito Santo",
    "Goias",
    "Maranhao",
    "Mato Grosso",
    "Mato Grosso do Sul",
    "Minas Gerais",
    "Para",
    "Paraiba",
    "Parana",
    "Pernambuco",
    "Piaui",
    "Rio de Janeiro",
    "Rio Grande do Norte",
    "Rio Grande do Sul",
    "Rondonia",
    "Roraima",
    "Santa Catarina",
    "Sao Paulo",
    "Sergipe",
    "Tocantins",
  ],
  "British Indian Ocean Territory (the)": [
    "Belait",
    "Brunei and Muara",
    "Temburong",
    "Tutong",
  ],
  "Brunei Darussalam": null,
  Bulgaria: [
    "Blagoevgrad",
    "Burgas",
    "Dobrich",
    "Gabrovo",
    "Khaskovo",
    "Kurdzhali",
    "Kyustendil",
    "Lovech",
    "Montana",
    "Pazardzhik",
    "Pernik",
    "Pleven",
    "Plovdiv",
    "Razgrad",
    "Ruse",
    "Shumen",
    "Silistra",
    "Sliven",
    "Smolyan",
    "Sofiya",
    "Sofiya-Grad",
    "Stara Zagora",
    "Turgovishte",
    "Varna",
    "Veliko Turnovo",
    "Vidin",
    "Vratsa",
    "Yambol",
  ],
  "Burkina Faso": [
    "Bale",
    "Bam",
    "Banwa",
    "Bazega",
    "Bougouriba",
    "Boulgou",
    "Boulkiemde",
    "Comoe",
    "Ganzourgou",
    "Gnagna",
    "Gourma",
    "Houet",
    "Ioba",
    "Kadiogo",
    "Kenedougou",
    "Komondjari",
    "Kompienga",
    "Kossi",
    "Koulpelogo",
    "Kouritenga",
    "Kourweogo",
    "Leraba",
    "Loroum",
    "Mouhoun",
    "Namentenga",
    "Nahouri",
    "Nayala",
    "Noumbiel",
    "Oubritenga",
    "Oudalan",
    "Passore",
    "Poni",
    "Sanguie",
    "Sanmatenga",
    "Seno",
    "Sissili",
    "Soum",
    "Sourou",
    "Tapoa",
    "Tuy",
    "Yagha",
    "Yatenga",
    "Ziro",
    "Zondoma",
    "Zoundweogo",
  ],
  Burma: [
    "Ayeyarwady",
    "Bago",
    "Magway",
    "Mandalay",
    "Sagaing",
    "Tanintharyi",
    "Yangon",
    "Chin State",
    "Kachin State",
    "Kayin State",
    "Kayah State",
    "Mon State",
    "Rakhine State",
    "Shan State",
  ],
  Burundi: [
    "Bubanza",
    "Bujumbura Mairie",
    "Bujumbura Rural",
    "Bururi",
    "Cankuzo",
    "Cibitoke",
    "Gitega",
    "Karuzi",
    "Kayanza",
    "Kirundo",
    "Makamba",
    "Muramvya",
    "Muyinga",
    "Mwaro",
    "Ngozi",
    "Rutana",
    "Ruyigi",
  ],
  Cambodia: [
    "Banteay Mean Chey",
    "Batdambang",
    "Kampong Cham",
    "Kampong Chhnang",
    "Kampong Spoe",
    "Kampong Thum",
    "Kampot",
    "Kandal",
    "Koh Kong",
    "Kracheh",
    "Mondol Kiri",
    "Otdar Mean Chey",
    "Pouthisat",
    "Preah Vihear",
    "Prey Veng",
    "Rotanakir",
    "Siem Reab",
    "Stoeng Treng",
    "Svay Rieng",
    "Takao",
    "Keb",
    "Pailin",
    "Phnom Penh",
    "Preah Seihanu",
  ],
  Cameroon: [
    "Adamaoua",
    "Centre",
    "Est",
    "Extreme-Nord",
    "Littoral",
    "Nord",
    "Nord-Ouest",
    "Ouest",
    "Sud",
    "Sud-Ouest",
  ],
  Canada: [
    "Alberta",
    "British Columbia",
    "Manitoba",
    "New Brunswick",
    "Newfoundland and Labrador",
    "Northwest Territories",
    "Nova Scotia",
    "Nunavut",
    "Ontario",
    "Prince Edward Island",
    "Quebec",
    "Saskatchewan",
    "Yukon Territory",
  ],
  "Cape Verde": [
    "Santo Antão",
    "São Vicente",
    "Santa Luzia,",
    "São Nicolau",
    "Sal",
    "Boa Vista",
    "Maio",
    "Santiago",
    "Fogo",
    "Brava",
  ],
  "Cayman Islands (the)": null,
  "Central African Republic (the)": [
    "Bamingui-Bangoran",
    "Bangui",
    "Basse-Kotto",
    "Haute-Kotto",
    "Haut-Mbomou",
    "Kemo",
    "Lobaye",
    "Mambere-Kadei",
    "Mbomou",
    "Nana-Grebizi",
    "Nana-Mambere",
    "Ombella-Mpoko",
    "Ouaka",
    "Ouham",
    "Ouham-Pende",
    "Sangha-Mbaere",
    "Vakaga",
  ],
  Chad: [
    "Batha",
    "Biltine",
    "Borkou-Ennedi-Tibesti",
    "Chari-Baguirmi",
    "Guéra",
    "Kanem",
    "Lac",
    "Logone Occidental",
    "Logone Oriental",
    "Mayo-Kebbi",
    "Moyen-Chari",
    "Ouaddaï",
    "Salamat",
    "Tandjile",
  ],
  Chile: [
    "Aysen",
    "Antofagasta",
    "Araucania",
    "Atacama",
    "Bio-Bio",
    "Coquimbo",
    "O'Higgins",
    "Los Lagos",
    "Magallanes y la Antartica Chilena",
    "Maule",
    "Santiago Region Metropolitana",
    "Tarapaca",
    "Valparaiso",
  ],
  China: [
    "Anhui",
    "Fujian",
    "Gansu",
    "Guangdong",
    "Guizhou",
    "Hainan",
    "Hebei",
    "Heilongjiang",
    "Henan",
    "Hubei",
    "Hunan",
    "Jiangsu",
    "Jiangxi",
    "Jilin",
    "Liaoning",
    "Qinghai",
    "Shaanxi",
    "Shandong",
    "Shanxi",
    "Sichuan",
    "Yunnan",
    "Zhejiang",
    "Guangxi",
    "Nei Mongol",
    "Ningxia",
    "Xinjiang",
    "Xizang (Tibet)",
    "Beijing",
    "Chongqing",
    "Shanghai",
    "Tianjin",
  ],
  "Christmas Island": null,
  "Cocos (Keeling) Islands (the)": null,
  Colombia: [
    "Amazonas",
    "Antioquia",
    "Arauca",
    "Atlantico",
    "Bogota District Capital",
    "Bolivar",
    "Boyaca",
    "Caldas",
    "Caqueta",
    "Casanare",
    "Cauca",
    "Cesar",
    "Choco",
    "Cordoba",
    "Cundinamarca",
    "Guainia",
    "Guaviare",
    "Huila",
    "La Guajira",
    "Magdalena",
    "Meta",
    "Narino",
    "Norte de Santander",
    "Putumayo",
    "Quindio",
    "Risaralda",
    "San Andres & Providencia",
    "Santander",
    "Sucre",
    "Tolima",
    "Valle del Cauca",
    "Vaupes",
    "Vichada",
  ],
  "Comoros (the)": [
    "Grande Comore (Njazidja)",
    "Anjouan (Nzwani)",
    "Moheli (Mwali)",
  ],
  "Congo (the Democratic Republic)": [
    "Bandundu",
    "Bas-Congo",
    "Equateur",
    "Kasai-Occidental",
    "Kasai-Oriental",
    "Katanga",
    "Kinshasa",
    "Maniema",
    "Nord-Kivu",
    "Orientale",
    "Sud-Kivu",
  ],
  "Congo (the)": [
    "Bouenza",
    "Brazzaville",
    "Cuvette",
    "Cuvette-Ouest",
    "Kouilou",
    "Lekoumou",
    "Likouala",
    "Niari",
    "Plateaux",
    "Pool",
    "Sangha",
  ],
  "Cook Islands (the)": null,
  "Costa Rica": [
    "Alajuela",
    "Cartago",
    "Guanacaste",
    "Heredia",
    "Limon",
    "Puntarenas",
    "San Jose",
  ],
  Croatia: [
    "Bjelovarsko-Bilogorska",
    "Brodsko-Posavska",
    "Dubrovacko-Neretvanska",
    "Istarska",
    "Karlovacka",
    "Koprivnicko-Krizevacka",
    "Krapinsko-Zagorska",
    "Licko-Senjska",
    "Medimurska",
    "Osjecko-Baranjska",
    "Pozesko-Slavonska",
    "Primorsko-Goranska",
    "Sibensko-Kninska",
    "Sisacko-Moslavacka",
    "Splitsko-Dalmatinska",
    "Varazdinska",
    "Viroviticko-Podravska",
    "Vukovarsko-Srijemska",
    "Zadarska",
    "Zagreb",
    "Zagrebacka",
  ],
  Cuba: [
    "Camaguey",
    "Ciego de Avila",
    "Cienfuegos",
    "Ciudad de La Habana",
    "Granma",
    "Guantanamo",
    "Holguin",
    "Isla de la Juventud",
    "La Habana",
    "Las Tunas",
    "Matanzas",
    "Pinar del Rio",
    "Sancti Spiritus",
    "Santiago de Cuba",
    "Villa Clara",
  ],
  Curaçao: null,
  Cyprus: ["Famagusta", "Kyrenia", "Larnaca", "Limassol", "Nicosia", "Paphos"],
  Czechia: [
    "Jihocesky Kraj",
    "Jihomoravsky Kraj",
    "Karlovarsky Kraj",
    "Kralovehradecky Kraj",
    "Liberecky Kraj",
    "Moravskoslezsky Kraj",
    "Olomoucky Kraj",
    "Pardubicky Kraj",
    "Plzensky Kraj",
    "Praha",
    "Stredocesky Kraj",
    "Ustecky Kraj",
    "Vysocina",
    "Zlinsky Kraj",
  ],
  "Côte d'Ivoire": [
    "Abidjan",
    "Bas-Sassandra",
    "Comoé",
    "Denguélé",
    "Gôh-Djiboua",
    "Lacs",
    "Lagunes",
    "Montagnes",
    "Sassandra-Marahoué",
    "Savanes",
    "Vallée du Bandama",
    "Woroba",
    "Yamoussoukro",
    "Zanzan",
  ],
  Denmark: [
    "Arhus",
    "Bornholm",
    "Frederiksberg",
    "Frederiksborg",
    "Fyn",
    "Kobenhavn",
    "Kobenhavns",
    "Nordjylland",
    "Ribe",
    "Ringkobing",
    "Roskilde",
    "Sonderjylland",
    "Storstrom",
    "Vejle",
    "Vestsjalland",
    "Viborg",
  ],
  Djibouti: ["Ali Sabih", "Dikhil", "Djibouti", "Obock", "Tadjoura"],
  Dominica: [
    "Saint Andrew",
    "Saint David",
    "Saint George",
    "Saint John",
    "Saint Joseph",
    "Saint Luke",
    "Saint Mark",
    "Saint Patrick",
    "Saint Paul",
    "Saint Peter",
  ],
  "Dominican Republic (the)": [
    "Azua",
    "Baoruco",
    "Barahona",
    "Dajabon",
    "Distrito Nacional",
    "Duarte",
    "Elias Pina",
    "El Seibo",
    "Espaillat",
    "Hato Mayor",
    "Independencia",
    "La Altagracia",
    "La Romana",
    "La Vega",
    "Maria Trinidad Sanchez",
    "Monsenor Nouel",
    "Monte Cristi",
    "Monte Plata",
    "Pedernales",
    "Peravia",
    "Puerto Plata",
    "Salcedo",
    "Samana",
    "Sanchez Ramirez",
    "San Cristobal",
    "San Jose de Ocoa",
    "San Juan",
    "San Pedro de Macoris",
    "Santiago",
    "Santiago Rodriguez",
    "Santo Domingo",
    "Valverde",
  ],
  "East Timor": [
    "Aileu",
    "Ainaro",
    "Baucau",
    "Bobonaro",
    "Cova-Lima",
    "Dili",
    "Ermera",
    "Lautem",
    "Liquica",
    "Manatuto",
    "Manufahi",
    "Oecussi",
    "Viqueque",
  ],
  Ecuador: [
    "Azuay",
    "Bolivar",
    "Canar",
    "Carchi",
    "Chimborazo",
    "Cotopaxi",
    "El Oro",
    "Esmeraldas",
    "Galapagos",
    "Guayas",
    "Imbabura",
    "Loja",
    "Los Rios",
    "Manabi",
    "Morona-Santiago",
    "Napo",
    "Orellana",
    "Pastaza",
    "Pichincha",
    "Sucumbios",
    "Tungurahua",
    "Zamora-Chinchipe",
  ],
  Egypt: [
    "Ad Daqahliyah",
    "Al Bahr al Ahmar",
    "Al Buhayrah",
    "Al Fayyum",
    "Al Gharbiyah",
    "Al Iskandariyah",
    "Al Isma'iliyah",
    "Al Jizah",
    "Al Minufiyah",
    "Al Minya",
    "Al Qahirah",
    "Al Qalyubiyah",
    "Al Wadi al Jadid",
    "Ash Sharqiyah",
    "As Suways",
    "Aswan",
    "Asyut",
    "Bani Suwayf",
    "Bur Sa'id",
    "Dumyat",
    "Janub Sina'",
    "Kafr ash Shaykh",
    "Matruh",
    "Qina",
    "Shamal Sina'",
    "Suhaj",
  ],
  "El Salvador": [
    "Ahuachapan",
    "Cabanas",
    "Chalatenango",
    "Cuscatlan",
    "La Libertad",
    "La Paz",
    "La Union",
    "Morazan",
    "San Miguel",
    "San Salvador",
    "Santa Ana",
    "San Vicente",
    "Sonsonate",
    "Usulutan",
  ],
  "Equatorial Guinea": [
    "Annobon",
    "Bioko Norte",
    "Bioko Sur",
    "Centro Sur",
    "Kie-Ntem",
    "Litoral",
    "Wele-Nzas",
  ],
  Eritrea: [
    "Anseba",
    "Debub",
    "Debubawi K'eyih Bahri",
    "Gash Barka",
    "Ma'akel",
    "Semenawi Keyih Bahri",
  ],
  Estonia: [
    "Harjumaa (Tallinn)",
    "Hiiumaa (Kardla)",
    "Ida-Virumaa (Johvi)",
    "Jarvamaa (Paide)",
    "Jogevamaa (Jogeva)",
    "Laanemaa (Haapsalu)",
    "Laane-Virumaa (Rakvere)",
    "Parnumaa (Parnu)",
    "Polvamaa (Polva)",
    "Raplamaa (Rapla)",
    "Saaremaa (Kuressaare)",
    "Tartumaa (Tartu)",
    "Valgamaa (Valga)",
    "Viljandimaa (Viljandi)",
    "Vorumaa (Voru)",
  ],
  Eswatini: null,
  Ethiopia: [
    "Addis Ababa",
    "Afar",
    "Amhara",
    "Binshangul Gumuz",
    "Dire Dawa",
    "Gambela Hizboch",
    "Harari",
    "Oromia",
    "Somali",
    "Tigray",
    "Southern Nations, Nationalities, and Peoples Region",
  ],
  "Falkland Islands (the) [Malvinas]": null,
  "Faroe Islands (the)": null,
  Fiji: [
    "Central (Suva)",
    "Eastern (Levuka)",
    "Northern (Labasa)",
    "Rotuma",
    "Western (Lautoka)",
  ],
  Finland: [
    "Aland",
    "Etela-Suomen Laani",
    "Ita-Suomen Laani",
    "Lansi-Suomen Laani",
    "Lappi",
    "Oulun Laani",
  ],
  France: [
    "Alsace",
    "Aquitaine",
    "Auvergne",
    "Basse-Normandie",
    "Bourgogne",
    "Bretagne",
    "Centre",
    "Champagne-Ardenne",
    "Corse",
    "Franche-Comte",
    "Haute-Normandie",
    "Ile-de-France",
    "Languedoc-Roussillon",
    "Limousin",
    "Lorraine",
    "Midi-Pyrenees",
    "Nord-Pas-de-Calais",
    "Pays de la Loire",
    "Picardie",
    "Poitou-Charentes",
    "Provence-Alpes-Cote d'Azur",
    "Rhone-Alpes",
  ],
  "French Guiana": null,
  "French Polynesia": null,
  "French Southern Territories (the)": null,
  Gabon: [
    "Estuaire",
    "Haut-Ogooue",
    "Moyen-Ogooue",
    "Ngounie",
    "Nyanga",
    "Ogooue-Ivindo",
    "Ogooue-Lolo",
    "Ogooue-Maritime",
    "Woleu-Ntem",
  ],
  "Gambia (the)": [
    "Banjul",
    "Central River",
    "Lower River",
    "North Bank",
    "Upper River",
    "Western",
  ],
  Georgia: [
    "Abkhazia",
    "Adjara",
    "Guria",
    "Imereti",
    "Kakheti",
    "Kvemo Kartli",
    "Mtskheta-Mtianeti",
    "Racha-Lechkhumi and Kvemo Svaneti",
    "Samegrelo-Zemo Svaneti",
    "Samtskhe-Javakheti",
    "Shida Kartli",
    "Tbilisi",
  ],
  Germany: [
    "Baden-Wuerttemberg",
    "Bayern",
    "Berlin",
    "Brandenburg",
    "Bremen",
    "Hamburg",
    "Hessen",
    "Mecklenburg-Vorpommern",
    "Niedersachsen",
    "Nordrhein-Westfalen",
    "Rheinland-Pfalz",
    "Saarland",
    "Sachsen",
    "Sachsen-Anhalt",
    "Schleswig-Holstein",
    "Thueringen",
  ],
  Ghana: [
    "Ashanti",
    "Brong-Ahafo",
    "Central",
    "Eastern",
    "Greater Accra",
    "Northern",
    "Upper East",
    "Upper West",
    "Volta",
    "Western",
  ],
  Gibraltar: null,
  Greece: [
    "Agion Oros",
    "Achaia",
    "Aitolia kai Akarmania",
    "Argolis",
    "Arkadia",
    "Arta",
    "Attiki",
    "Chalkidiki",
    "Chanion",
    "Chios",
    "Dodekanisos",
    "Drama",
    "Evros",
    "Evrytania",
    "Evvoia",
    "Florina",
    "Fokidos",
    "Fthiotis",
    "Grevena",
    "Ileia",
    "Imathia",
    "Ioannina",
    "Irakleion",
    "Karditsa",
    "Kastoria",
    "Kavala",
    "Kefallinia",
    "Kerkyra",
    "Kilkis",
    "Korinthia",
    "Kozani",
    "Kyklades",
    "Lakonia",
    "Larisa",
    "Lasithi",
    "Lefkas",
    "Lesvos",
    "Magnisia",
    "Messinia",
    "Pella",
    "Pieria",
    "Preveza",
    "Rethynnis",
    "Rodopi",
    "Samos",
    "Serrai",
    "Thesprotia",
    "Thessaloniki",
    "Trikala",
    "Voiotia",
    "Xanthi",
    "Zakynthos",
  ],
  Greenland: [
    "Avannaa (Nordgronland)",
    "Tunu (Ostgronland)",
    "Kitaa (Vestgronland)",
  ],
  Grenada: [
    "Carriacou and Petit Martinique",
    "Saint Andrew",
    "Saint David",
    "Saint George",
    "Saint John",
    "Saint Mark",
    "Saint Patrick",
  ],
  Guadeloupe: null,
  Guam: null,
  Guatemala: [
    "Alta Verapaz",
    "Baja Verapaz",
    "Chimaltenango",
    "Chiquimula",
    "El Progreso",
    "Escuintla",
    "Guatemala",
    "Huehuetenango",
    "Izabal",
    "Jalapa",
    "Jutiapa",
    "Peten",
    "Quetzaltenango",
    "Quiche",
    "Retalhuleu",
    "Sacatepequez",
    "San Marcos",
    "Santa Rosa",
    "Solola",
    "Suchitepequez",
    "Totonicapan",
    "Zacapa",
  ],
  Guernsey: null,
  Guinea: [
    "Beyla",
    "Boffa",
    "Boke",
    "Conakry",
    "Coyah",
    "Dabola",
    "Dalaba",
    "Dinguiraye",
    "Dubreka",
    "Faranah",
    "Forecariah",
    "Fria",
    "Gaoual",
    "Gueckedou",
    "Kankan",
    "Kerouane",
    "Kindia",
    "Kissidougou",
    "Koubia",
    "Koundara",
    "Kouroussa",
    "Labe",
    "Lelouma",
    "Lola",
    "Macenta",
    "Mali",
    "Mamou",
    "Mandiana",
    "Nzerekore",
    "Pita",
    "Siguiri",
    "Telimele",
    "Tougue",
    "Yomou",
  ],
  "Guinea-Bissau": [
    "Bafata",
    "Biombo",
    "Bissau",
    "Bolama",
    "Cacheu",
    "Gabu",
    "Oio",
    "Quinara",
    "Tombali",
  ],
  Guyana: [
    "Barima-Waini",
    "Cuyuni-Mazaruni",
    "Demerara-Mahaica",
    "East Berbice-Corentyne",
    "Essequibo Islands-West Demerara",
    "Mahaica-Berbice",
    "Pomeroon-Supenaam",
    "Potaro-Siparuni",
    "Upper Demerara-Berbice",
    "Upper Takutu-Upper Essequibo",
  ],
  Haiti: [
    "Artibonite",
    "Centre",
    "Grand 'Anse",
    "Nord",
    "Nord-Est",
    "Nord-Ouest",
    "Ouest",
    "Sud",
    "Sud-Est",
  ],
  "Heard Island and McDonald Islands": null,
  "Holy See (the)": null,
  Honduras: [
    "Atlantida",
    "Choluteca",
    "Colon",
    "Comayagua",
    "Copan",
    "Cortes",
    "El Paraiso",
    "Francisco Morazan",
    "Gracias a Dios",
    "Intibuca",
    "Islas de la Bahia",
    "La Paz",
    "Lempira",
    "Ocotepeque",
    "Olancho",
    "Santa Barbara",
    "Valle",
    "Yoro",
  ],
  "Hong Kong": [
    "Yuen Long District",
    "Tsuen Wan District",
    "Tai Po District",
    "Sai Kung District",
    "Islands District",
    "Central and Western District",
    "Wan Chai",
    "Eastern",
    "Southern",
    "North",
    "Yau Tsim Mong",
    "Sham Shui Po",
    "Kowloon City",
    "Wong Tai Sin",
    "Kwun Tong",
    "Kwai Tsing",
    "Tuen Mun",
    "Sha Tin",
  ],
  Hungary: [
    "Bacs-Kiskun",
    "Baranya",
    "Bekes",
    "Borsod-Abauj-Zemplen",
    "Csongrad",
    "Fejer",
    "Gyor-Moson-Sopron",
    "Hajdu-Bihar",
    "Heves",
    "Jasz-Nagykun-Szolnok",
    "Komarom-Esztergom",
    "Nograd",
    "Pest",
    "Somogy",
    "Szabolcs-Szatmar-Bereg",
    "Tolna",
    "Vas",
    "Veszprem",
    "Zala",
    "Bekescsaba",
    "Debrecen",
    "Dunaujvaros",
    "Eger",
    "Gyor",
    "Hodmezovasarhely",
    "Kaposvar",
    "Kecskemet",
    "Miskolc",
    "Nagykanizsa",
    "Nyiregyhaza",
    "Pecs",
    "Sopron",
    "Szeged",
    "Szekesfehervar",
    "Szolnok",
    "Szombathely",
    "Tatabanya",
    "Veszprem",
    "Zalaegerszeg",
  ],
  Iceland: [
    "Austurland",
    "Hofudhborgarsvaedhi",
    "Nordhurland Eystra",
    "Nordhurland Vestra",
    "Sudhurland",
    "Sudhurnes",
    "Vestfirdhir",
    "Vesturland",
  ],
  India: [
    "Andaman and Nicobar Islands",
    "Andhra Pradesh",
    "Arunachal Pradesh",
    "Assam",
    "Bihar",
    "Chandigarh",
    "Chhattisgarh",
    "Dadra and Nagar Haveli",
    "Daman and Diu",
    "Delhi",
    "Goa",
    "Gujarat",
    "Haryana",
    "Himachal Pradesh",
    "Jammu and Kashmir",
    "Jharkhand",
    "Karnataka",
    "Kerala",
    "Ladakh",
    "Lakshadweep",
    "Madhya Pradesh",
    "Maharashtra",
    "Manipur",
    "Meghalaya",
    "Mizoram",
    "Nagaland",
    "Orissa",
    "Pondicherry",
    "Punjab",
    "Rajasthan",
    "Sikkim",
    "Tamil Nadu",
    "Telangana",
    "Tripura",
    "Uttaranchal",
    "Uttar Pradesh",
    "West Bengal",
  ],
  Indonesia: [
    "Aceh",
    "Bali",
    "Banten",
    "Bengkulu",
    "Gorontalo",
    "Irian Jaya Barat",
    "Jakarta Raya",
    "Jambi",
    "Jawa Barat",
    "Jawa Tengah",
    "Jawa Timur",
    "Kalimantan Barat",
    "Kalimantan Selatan",
    "Kalimantan Tengah",
    "Kalimantan Timur",
    "Kepulauan Bangka Belitung",
    "Kepulauan Riau",
    "Lampung",
    "Maluku",
    "Maluku Utara",
    "Nusa Tenggara Barat",
    "Nusa Tenggara Timur",
    "Papua",
    "Riau",
    "Sulawesi Barat",
    "Sulawesi Selatan",
    "Sulawesi Tengah",
    "Sulawesi Tenggara",
    "Sulawesi Utara",
    "Sumatera Barat",
    "Sumatera Selatan",
    "Sumatera Utara",
    "Yogyakarta",
  ],
  "Iran (Islamic Republic of)": [
    "Ardabil",
    "Azarbayjan-e Gharbi",
    "Azarbayjan-e Sharqi",
    "Bushehr",
    "Chahar Mahall va Bakhtiari",
    "Esfahan",
    "Fars",
    "Gilan",
    "Golestan",
    "Hamadan",
    "Hormozgan",
    "Ilam",
    "Kerman",
    "Kermanshah",
    "Khorasan-e Janubi",
    "Khorasan-e Razavi",
    "Khorasan-e Shemali",
    "Khuzestan",
    "Kohgiluyeh va Buyer Ahmad",
    "Kordestan",
    "Lorestan",
    "Markazi",
    "Mazandaran",
    "Qazvin",
    "Qom",
    "Semnan",
    "Sistan va Baluchestan",
    "Tehran",
    "Yazd",
    "Zanjan",
  ],
  Iraq: [
    "Al Anbar",
    "Al Basrah",
    "Al Muthanna",
    "Al Qadisiyah",
    "An Najaf",
    "Arbil",
    "As Sulaymaniyah",
    "At Ta'mim",
    "Babil",
    "Baghdad",
    "Dahuk",
    "Dhi Qar",
    "Diyala",
    "Karbala'",
    "Maysan",
    "Ninawa",
    "Salah ad Din",
    "Wasit",
  ],
  Ireland: [
    "Carlow",
    "Cavan",
    "Clare",
    "Cork",
    "Donegal",
    "Dublin",
    "Galway",
    "Kerry",
    "Kildare",
    "Kilkenny",
    "Laois",
    "Leitrim",
    "Limerick",
    "Longford",
    "Louth",
    "Mayo",
    "Meath",
    "Monaghan",
    "Offaly",
    "Roscommon",
    "Sligo",
    "Tipperary",
    "Waterford",
    "Westmeath",
    "Wexford",
    "Wicklow",
  ],
  "Isle of Man": null,
  Israel: ["Central", "Haifa", "Jerusalem", "Northern", "Southern", "Tel Aviv"],
  Italy: [
    "Abruzzo",
    "Basilicata",
    "Calabria",
    "Campania",
    "Emilia-Romagna",
    "Friuli-Venezia Giulia",
    "Lazio",
    "Liguria",
    "Lombardia",
    "Marche",
    "Molise",
    "Piemonte",
    "Puglia",
    "Sardegna",
    "Sicilia",
    "Toscana",
    "Trentino-Alto Adige",
    "Umbria",
    "Valle d'Aosta",
    "Veneto",
  ],
  Jamaica: [
    "Clarendon",
    "Hanover",
    "Kingston",
    "Manchester",
    "Portland",
    "Saint Andrew",
    "Saint Ann",
    "Saint Catherine",
    "Saint Elizabeth",
    "Saint James",
    "Saint Mary",
    "Saint Thomas",
    "Trelawny",
    "Westmoreland",
  ],
  Japan: [
    "Aichi",
    "Akita",
    "Aomori",
    "Chiba",
    "Ehime",
    "Fukui",
    "Fukuoka",
    "Fukushima",
    "Gifu",
    "Gumma",
    "Hiroshima",
    "Hokkaido",
    "Hyogo",
    "Ibaraki",
    "Ishikawa",
    "Iwate",
    "Kagawa",
    "Kagoshima",
    "Kanagawa",
    "Kochi",
    "Kumamoto",
    "Kyoto",
    "Mie",
    "Miyagi",
    "Miyazaki",
    "Nagano",
    "Nagasaki",
    "Nara",
    "Niigata",
    "Oita",
    "Okayama",
    "Okinawa",
    "Osaka",
    "Saga",
    "Saitama",
    "Shiga",
    "Shimane",
    "Shizuoka",
    "Tochigi",
    "Tokushima",
    "Tokyo",
    "Tottori",
    "Toyama",
    "Wakayama",
    "Yamagata",
    "Yamaguchi",
    "Yamanashi",
  ],
  Jersey: null,
  Jordan: [
    "Ajlun",
    "Al 'Aqabah",
    "Al Balqa'",
    "Al Karak",
    "Al Mafraq",
    "'Amman",
    "At Tafilah",
    "Az Zarqa'",
    "Irbid",
    "Jarash",
    "Ma'an",
    "Madaba",
  ],
  Kazakhstan: [
    "Almaty Oblysy",
    "Almaty Qalasy",
    "Aqmola Oblysy",
    "Aqtobe Oblysy",
    "Astana Qalasy",
    "Atyrau Oblysy",
    "Batys Qazaqstan Oblysy",
    "Bayqongyr Qalasy",
    "Mangghystau Oblysy",
    "Ongtustik Qazaqstan Oblysy",
    "Pavlodar Oblysy",
    "Qaraghandy Oblysy",
    "Qostanay Oblysy",
    "Qyzylorda Oblysy",
    "Shyghys Qazaqstan Oblysy",
    "Soltustik Qazaqstan Oblysy",
    "Zhambyl Oblysy",
  ],
  Kenya: [
    "Central",
    "Coast",
    "Eastern",
    "Nairobi Area",
    "North Eastern",
    "Nyanza",
    "Rift Valley",
    "Western",
  ],
  Kiribati: [
    "Banaba",
    "Tarawa",
    "Northern Gilbert Islands",
    "Central Gilbert Island",
    "Southern Gilbert Islands",
    "Line Islands",
  ],
  "Korea (the Democratic People's Republic of)": [
    "Chagang",
    "North Hamgyong",
    "South Hamgyong",
    "North Hwanghae",
    "South Hwanghae",
    "Kangwon",
    "North P'yongan",
    "South P'yongan",
    "Yanggang",
    "Kaesong",
    "Najin",
    "Namp'o",
    "Pyongyang",
  ],
  "Korea (the Republic of)": [
    "Seoul",
    "Busan City",
    "Daegu City",
    "Incheon City",
    "Gwangju City",
    "Daejeon City",
    "Ulsan",
    "Gyeonggi Province",
    "Gangwon Province",
    "North Chungcheong Province",
    "South Chungcheong Province",
    "North Jeolla Province",
    "South Jeolla Province",
    "North Gyeongsang Province",
    "South Gyeongsang Province",
    "Jeju",
  ],
  Kosovo: [
    "Ferizaj",
    "Gjakova",
    "Gjilan",
    "Mitrovica",
    "Peja",
    "Pristina",
    "Prizren",
  ],
  Kuwait: [
    "Al Ahmadi",
    "Al Farwaniyah",
    "Al Asimah",
    "Al Jahra",
    "Hawalli",
    "Mubarak Al-Kabeer",
  ],
  Kyrgyzstan: [
    "Batken Oblasty",
    "Bishkek Shaary",
    "Chuy Oblasty",
    "Jalal-Abad Oblasty",
    "Naryn Oblasty",
    "Osh Oblasty",
    "Talas Oblasty",
    "Ysyk-Kol Oblasty",
  ],
  "Lao People's Democratic Republic (the)": [
    "Attapu",
    "Bokeo",
    "Bolikhamxai",
    "Champasak",
    "Houaphan",
    "Khammouan",
    "Louangnamtha",
    "Louangphrabang",
    "Oudomxai",
    "Phongsali",
    "Salavan",
    "Savannakhet",
    "Viangchan",
    "Viangchan",
    "Xaignabouli",
    "Xaisomboun",
    "Xekong",
    "Xiangkhoang",
  ],
  Latvia: [
    "Aizkraukles Rajons",
    "Aluksnes Rajons",
    "Balvu Rajons",
    "Bauskas Rajons",
    "Cesu Rajons",
    "Daugavpils",
    "Daugavpils Rajons",
    "Dobeles Rajons",
    "Gulbenes Rajons",
    "Jekabpils Rajons",
    "Jelgava",
    "Jelgavas Rajons",
    "Jurmala",
    "Kraslavas Rajons",
    "Kuldigas Rajons",
    "Liepaja",
    "Liepajas Rajons",
    "Limbazu Rajons",
    "Ludzas Rajons",
    "Madonas Rajons",
    "Ogres Rajons",
    "Preilu Rajons",
    "Rezekne",
    "Rezeknes Rajons",
    "Riga",
    "Rigas Rajons",
    "Saldus Rajons",
    "Talsu Rajons",
    "Tukuma Rajons",
    "Valkas Rajons",
    "Valmieras Rajons",
    "Ventspils",
    "Ventspils Rajons",
  ],
  Lebanon: [
    "Beyrouth",
    "Beqaa",
    "Liban-Nord",
    "Liban-Sud",
    "Mont-Liban",
    "Nabatiye",
  ],
  Lesotho: [
    "Berea",
    "Butha-Buthe",
    "Leribe",
    "Mafeteng",
    "Maseru",
    "Mohale's Hoek",
    "Mokhotlong",
    "Qacha's Nek",
    "Quthing",
    "Thaba-Tseka",
  ],
  Liberia: [
    "Bomi",
    "Bong",
    "Gbarpolu",
    "Grand Bassa",
    "Grand Cape Mount",
    "Grand Gedeh",
    "Grand Kru",
    "Lofa",
    "Margibi",
    "Maryland",
    "Montserrado",
    "Nimba",
    "River Cess",
    "River Gee",
    "Sinoe",
  ],
  Libya: [
    "Ajdabiya",
    "Al 'Aziziyah",
    "Al Fatih",
    "Al Jabal al Akhdar",
    "Al Jufrah",
    "Al Khums",
    "Al Kufrah",
    "An Nuqat al Khams",
    "Ash Shati'",
    "Awbari",
    "Az Zawiyah",
    "Banghazi",
    "Darnah",
    "Ghadamis",
    "Gharyan",
    "Misratah",
    "Murzuq",
    "Sabha",
    "Sawfajjin",
    "Surt",
    "Tarabulus",
    "Tarhunah",
    "Tubruq",
    "Yafran",
    "Zlitan",
  ],
  Liechtenstein: [
    "Balzers",
    "Eschen",
    "Gamprin",
    "Mauren",
    "Planken",
    "Ruggell",
    "Schaan",
    "Schellenberg",
    "Triesen",
    "Triesenberg",
    "Vaduz",
  ],
  Lithuania: [
    "Alytaus",
    "Kauno",
    "Klaipedos",
    "Marijampoles",
    "Panevezio",
    "Siauliu",
    "Taurages",
    "Telsiu",
    "Utenos",
    "Vilniaus",
  ],
  Luxembourg: ["Diekirch", "Grevenmacher", "Luxembourg"],
  Macao: null,
  Macedonia: [
    "Aerodrom",
    "Aracinovo",
    "Berovo",
    "Bitola",
    "Bogdanci",
    "Bogovinje",
    "Bosilovo",
    "Brvenica",
    "Butel",
    "Cair",
    "Caska",
    "Centar",
    "Centar Zupa",
    "Cesinovo",
    "Cucer-Sandevo",
    "Debar",
    "Debartsa",
    "Delcevo",
    "Demir Hisar",
    "Demir Kapija",
    "Dojran",
    "Dolneni",
    "Drugovo",
    "Gazi Baba",
    "Gevgelija",
    "Gjorce Petrov",
    "Gostivar",
    "Gradsko",
    "Ilinden",
    "Jegunovce",
    "Karbinci",
    "Karpos",
    "Kavadarci",
    "Kicevo",
    "Kisela Voda",
    "Kocani",
    "Konce",
    "Kratovo",
    "Kriva Palanka",
    "Krivogastani",
    "Krusevo",
    "Kumanovo",
    "Lipkovo",
    "Lozovo",
    "Makedonska Kamenica",
    "Makedonski Brod",
    "Mavrovo i Rastusa",
    "Mogila",
    "Negotino",
    "Novaci",
    "Novo Selo",
    "Ohrid",
    "Oslomej",
    "Pehcevo",
    "Petrovec",
    "Plasnica",
    "Prilep",
    "Probistip",
    "Radovis",
    "Rankovce",
    "Resen",
    "Rosoman",
    "Saraj",
    "Skopje",
    "Sopiste",
    "Staro Nagoricane",
    "Stip",
    "Struga",
    "Strumica",
    "Studenicani",
    "Suto Orizari",
    "Sveti Nikole",
    "Tearce",
    "Tetovo",
    "Valandovo",
    "Vasilevo",
    "Veles",
    "Vevcani",
    "Vinica",
    "Vranestica",
    "Vrapciste",
    "Zajas",
    "Zelenikovo",
    "Zelino",
    "Zrnovci",
  ],
  Madagascar: [
    "Antananarivo",
    "Antsiranana",
    "Fianarantsoa",
    "Mahajanga",
    "Toamasina",
    "Toliara",
  ],
  Malawi: [
    "Balaka",
    "Blantyre",
    "Chikwawa",
    "Chiradzulu",
    "Chitipa",
    "Dedza",
    "Dowa",
    "Karonga",
    "Kasungu",
    "Likoma",
    "Lilongwe",
    "Machinga",
    "Mangochi",
    "Mchinji",
    "Mulanje",
    "Mwanza",
    "Mzimba",
    "Ntcheu",
    "Nkhata Bay",
    "Nkhotakota",
    "Nsanje",
    "Ntchisi",
    "Phalombe",
    "Rumphi",
    "Salima",
    "Thyolo",
    "Zomba",
  ],
  Malaysia: [
    "Johor",
    "Kedah",
    "Kelantan",
    "Kuala Lumpur",
    "Labuan",
    "Malacca",
    "Negeri Sembilan",
    "Pahang",
    "Perak",
    "Perlis",
    "Penang",
    "Sabah",
    "Sarawak",
    "Selangor",
    "Terengganu",
  ],
  Maldives: [
    "Alifu",
    "Baa",
    "Dhaalu",
    "Faafu",
    "Gaafu Alifu",
    "Gaafu Dhaalu",
    "Gnaviyani",
    "Haa Alifu",
    "Haa Dhaalu",
    "Kaafu",
    "Laamu",
    "Lhaviyani",
    "Maale",
    "Meemu",
    "Noonu",
    "Raa",
    "Seenu",
    "Shaviyani",
    "Thaa",
    "Vaavu",
  ],
  Mali: [
    "Bamako (Capital)",
    "Gao",
    "Kayes",
    "Kidal",
    "Koulikoro",
    "Mopti",
    "Segou",
    "Sikasso",
    "Tombouctou",
  ],
  Malta: [
    "Southern Harbour",
    "Northern Harbour",
    "Western District",
    "Northern District",
    "Gozo and Comino",
  ],
  "Marshall Islands (the)": [
    "Ailuk",
    "Ailinglaplap",
    "Arno",
    "Aur",
    "Ebon",
    "Enewetak",
    "Jabat",
    "Jaluit",
    "Kili",
    "Kwajalein",
    "Lae",
    "Lib",
    "Likiep",
    "Majuro",
    "Maloelap",
    "Mejit",
    "Mili",
    "Namorik",
    "Namu",
    "Rongelap",
    "Ujae",
    "Utirik",
    "Wotho",
    "Wotje",
    "Ailinginae",
    "Bikar",
    "Bikini",
    "Bokak",
    "Erikub",
    "Jemo",
    "Rongrik",
    "Toke",
    "Ujelang",
  ],
  Martinique: null,
  Mauritania: [
    "Adrar",
    "Assaba",
    "Brakna",
    "Dakhlet Nouadhibou",
    "Gorgol",
    "Guidimaka",
    "Hodh Ech Chargui",
    "Hodh El Gharbi",
    "Inchiri",
    "Nouakchott",
    "Tagant",
    "Tiris Zemmour",
    "Trarza",
  ],
  Mauritius: [
    "Agalega Islands",
    "Black River",
    "Cargados Carajos Shoals",
    "Flacq",
    "Grand Port",
    "Moka",
    "Pamplemousses",
    "Plaines Wilhems",
    "Port Louis",
    "Riviere du Rempart",
    "Rodrigues",
    "Savanne",
  ],
  Mayotte: null,
  Mexico: [
    "Aguascalientes",
    "Baja California",
    "Baja California Sur",
    "Campeche",
    "Chiapas",
    "Chihuahua",
    "Coahuila de Zaragoza",
    "Colima",
    "Distrito Federal",
    "Durango",
    "Guanajuato",
    "Guerrero",
    "Hidalgo",
    "Jalisco",
    "Mexico",
    "Michoacan de Ocampo",
    "Morelos",
    "Nayarit",
    "Nuevo Leon",
    "Oaxaca",
    "Puebla",
    "Queretaro de Arteaga",
    "Quintana Roo",
    "San Luis Potosi",
    "Sinaloa",
    "Sonora",
    "Tabasco",
    "Tamaulipas",
    "Tlaxcala",
    "Veracruz-Llave",
    "Yucatan",
    "Zacatecas",
  ],
  "Micronesia (Federated States of)": null,
  "Moldova (the Republic of)": [
    "Anenii Noi",
    "Basarabeasca",
    "Briceni",
    "Cahul",
    "Cantemir",
    "Calarasi",
    "Causeni",
    "Cimislia",
    "Criuleni",
    "Donduseni",
    "Drochia",
    "Dubasari",
    "Edinet",
    "Falesti",
    "Floresti",
    "Glodeni",
    "Hincesti",
    "Ialoveni",
    "Leova",
    "Nisporeni",
    "Ocnita",
    "Orhei",
    "Rezina",
    "Riscani",
    "Singerei",
    "Soldanesti",
    "Soroca",
    "Stefan-Voda",
    "Straseni",
    "Taraclia",
    "Telenesti",
    "Ungheni",
    "Balti",
    "Bender",
    "Chisinau",
    "Gagauzia",
    "Stinga Nistrului",
  ],
  Monaco: ["Monaco-Ville", "La Condamine", "Monte Carlo", "Fontvieille"],
  Mongolia: [
    "Arhangay",
    "Bayanhongor",
    "Bayan-Olgiy",
    "Bulgan",
    "Darhan Uul",
    "Dornod",
    "Dornogovi",
    "Dundgovi",
    "Dzavhan",
    "Govi-Altay",
    "Govi-Sumber",
    "Hentiy",
    "Hovd",
    "Hovsgol",
    "Omnogovi",
    "Orhon",
    "Ovorhangay",
    "Selenge",
    "Suhbaatar",
    "Tov",
    "Ulaanbaatar",
    "Uvs",
  ],
  Montenegro: [
    "Andrijevica",
    "Bar",
    "Berane",
    "Berane",
    "Bijelo Polje",
    "Budva",
    "Cetinje",
    "Danilovgrad",
    "Gusinje",
    "Herceg Novi",
    "Kolašin",
    "Kotor",
    "Mojkovac",
    "Nikšić",
    "Petnjica",
    "Plav",
    "Pljevlja",
    "Plužine",
    "Podgorica",
    "Rožaje",
    "Šavnik",
    "Tivat",
    "Tuzi",
    "Ulcinj",
    "Žabljak",
  ],
  Montserrat: null,
  Morocco: [
    "Agadir",
    "Al Hoceima",
    "Azilal",
    "Beni Mellal",
    "Ben Slimane",
    "Boulemane",
    "Casablanca",
    "Chaouen",
    "El Jadida",
    "El Kelaa des Sraghna",
    "Er Rachidia",
    "Essaouira",
    "Fes",
    "Figuig",
    "Guelmim",
    "Ifrane",
    "Kenitra",
    "Khemisset",
    "Khenifra",
    "Khouribga",
    "Laayoune",
    "Larache",
    "Marrakech",
    "Meknes",
    "Nador",
    "Ouarzazate",
    "Oujda",
    "Rabat-Sale",
    "Safi",
    "Settat",
    "Sidi Kacem",
    "Tangier",
    "Tan-Tan",
    "Taounate",
    "Taroudannt",
    "Tata",
    "Taza",
    "Tetouan",
    "Tiznit",
  ],
  Mozambique: [
    "Cabo Delgado",
    "Gaza",
    "Inhambane",
    "Manica",
    "Maputo",
    "Cidade de Maputo",
    "Nampula",
    "Niassa",
    "Sofala",
    "Tete",
    "Zambezia",
  ],
  Myanmar: null,
  Namibia: [
    "Caprivi",
    "Erongo",
    "Hardap",
    "Karas",
    "Khomas",
    "Kunene",
    "Ohangwena",
    "Okavango",
    "Omaheke",
    "Omusati",
    "Oshana",
    "Oshikoto",
    "Otjozondjupa",
  ],
  Nauru: ["Aiwo", "Anabar", "Anetan", "Anibare"],
  Nepal: [
    "Bagmati",
    "Bheri",
    "Dhawalagiri",
    "Gandaki",
    "Janakpur",
    "Karnali",
    "Kosi",
    "Lumbini",
    "Mahakali",
    "Mechi",
    "Narayani",
    "Rapti",
    "Sagarmatha",
    "Seti",
  ],
  "Netherlands (the)": [
    "Drenthe",
    "Flevoland",
    "Friesland",
    "Gelderland",
    "Groningen",
    "Limburg",
    "Noord-Brabant",
    "Noord-Holland",
    "Overijssel",
    "Utrecht",
    "Zeeland",
    "Zuid-Holland",
  ],
  "New Caledonia": null,
  "New Zealand": [
    "Auckland",
    "Bay of Plenty",
    "Canterbury",
    "Chatham Islands",
    "Gisborne",
    "Hawke's Bay",
    "Manawatu-Wanganui",
    "Marlborough",
    "Nelson",
    "Northland",
    "Otago",
    "Southland",
    "Taranaki",
    "Tasman",
    "Waikato",
    "Wellington",
    "West Coast",
  ],
  Nicaragua: [
    "Atlantico Norte",
    "Atlantico Sur",
    "Boaco",
    "Carazo",
    "Chinandega",
    "Chontales",
    "Esteli",
    "Granada",
    "Jinotega",
    "Leon",
    "Madriz",
    "Managua",
    "Masaya",
    "Matagalpa",
    "Nueva Segovia",
    "Rio San Juan",
    "Rivas",
  ],
  "Niger (the)": [
    "Agadez",
    "Diffa",
    "Dosso",
    "Maradi",
    "Niamey",
    "Tahoua",
    "Tillaberi",
    "Zinder",
  ],
  Nigeria: [
    "Abia",
    "Abuja Federal Capital",
    "Adamawa",
    "Akwa Ibom",
    "Anambra",
    "Bauchi",
    "Bayelsa",
    "Benue",
    "Borno",
    "Cross River",
    "Delta",
    "Ebonyi",
    "Edo",
    "Ekiti",
    "Enugu",
    "Gombe",
    "Imo",
    "Jigawa",
    "Kaduna",
    "Kano",
    "Katsina",
    "Kebbi",
    "Kogi",
    "Kwara",
    "Lagos",
    "Nassarawa",
    "Niger",
    "Ogun",
    "Ondo",
    "Osun",
    "Oyo",
    "Plateau",
    "Rivers",
    "Sokoto",
    "Taraba",
    "Yobe",
    "Zamfara",
  ],
  Niue: null,
  "Norfolk Island": null,
  "Northern Mariana Islands (the)": null,
  Norway: [
    "Akershus",
    "Aust-Agder",
    "Buskerud",
    "Finnmark",
    "Hedmark",
    "Hordaland",
    "More og Romsdal",
    "Nordland",
    "Nord-Trondelag",
    "Oppland",
    "Oslo",
    "Ostfold",
    "Rogaland",
    "Sogn og Fjordane",
    "Sor-Trondelag",
    "Telemark",
    "Troms",
    "Vest-Agder",
    "Vestfold",
  ],
  Oman: [
    "Ad Dakhiliyah",
    "Al Batinah",
    "Al Wusta",
    "Ash Sharqiyah",
    "Az Zahirah",
    "Masqat",
    "Musandam",
    "Dhofar",
  ],
  Pakistan: [
    "Balochistan",
    "North-West Frontier Province",
    "Punjab",
    "Sindh",
    "Islamabad Capital Territory",
    "Federally Administered Tribal Areas",
  ],
  Palau: null,
  "Palestine, State of": null,
  Panama: [
    "Bocas del Toro",
    "Chiriqui",
    "Cocle",
    "Colon",
    "Darien",
    "Herrera",
    "Los Santos",
    "Panama",
    "San Blas",
    "Veraguas",
  ],
  "Papua New Guinea": [
    "Bougainville",
    "Central",
    "Chimbu",
    "Eastern Highlands",
    "East New Britain",
    "East Sepik",
    "Enga",
    "Gulf",
    "Madang",
    "Manus",
    "Milne Bay",
    "Morobe",
    "National Capital",
    "New Ireland",
    "Northern",
    "Sandaun",
    "Southern Highlands",
    "Western",
    "Western Highlands",
    "West New Britain",
  ],
  Paraguay: [
    "Alto Paraguay",
    "Alto Parana",
    "Amambay",
    "Asuncion",
    "Boqueron",
    "Caaguazu",
    "Caazapa",
    "Canindeyu",
    "Central",
    "Concepcion",
    "Cordillera",
    "Guaira",
    "Itapua",
    "Misiones",
    "Neembucu",
    "Paraguari",
    "Presidente Hayes",
    "San Pedro",
  ],
  Peru: [
    "Amazonas",
    "Ancash",
    "Apurimac",
    "Arequipa",
    "Ayacucho",
    "Cajamarca",
    "Callao",
    "Cusco",
    "Huancavelica",
    "Huanuco",
    "Ica",
    "Junin",
    "La Libertad",
    "Lambayeque",
    "Lima",
    "Loreto",
    "Madre de Dios",
    "Moquegua",
    "Pasco",
    "Piura",
    "Puno",
    "San Martin",
    "Tacna",
    "Tumbes",
    "Ucayali",
  ],
  "Philippines (the)": [
    "Abra",
    "Agusan del Norte",
    "Agusan del Sur",
    "Aklan",
    "Albay",
    "Antique",
    "Apayao",
    "Aurora",
    "Basilan",
    "Bataan",
    "Batanes",
    "Batangas",
    "Biliran",
    "Benguet",
    "Bohol",
    "Bukidnon",
    "Bulacan",
    "Cagayan",
    "Camarines Norte",
    "Camarines Sur",
    "Camiguin",
    "Capiz",
    "Catanduanes",
    "Cavite",
    "Cebu",
    "Compostela",
    "Davao del Norte",
    "Davao del Sur",
    "Davao Oriental",
    "Eastern Samar",
    "Guimaras",
    "Ifugao",
    "Ilocos Norte",
    "Ilocos Sur",
    "Iloilo",
    "Isabela",
    "Kalinga",
    "Laguna",
    "Lanao del Norte",
    "Lanao del Sur",
    "La Union",
    "Leyte",
    "Maguindanao",
    "Marinduque",
    "Masbate",
    "Mindoro Occidental",
    "Mindoro Oriental",
    "Misamis Occidental",
    "Misamis Oriental",
    "Mountain Province",
    "Negros Occidental",
    "Negros Oriental",
    "North Cotabato",
    "Northern Samar",
    "Nueva Ecija",
    "Nueva Vizcaya",
    "Palawan",
    "Pampanga",
    "Pangasinan",
    "Quezon",
    "Quirino",
    "Rizal",
    "Romblon",
    "Samar",
    "Sarangani",
    "Siquijor",
    "Sorsogon",
    "South Cotabato",
    "Southern Leyte",
    "Sultan Kudarat",
    "Sulu",
    "Surigao del Norte",
    "Surigao del Sur",
    "Tarlac",
    "Tawi-Tawi",
    "Zambales",
    "Zamboanga del Norte",
    "Zamboanga del Sur",
    "Zamboanga Sibugay",
  ],
  Pitcairn: null,
  Poland: [
    "Greater Poland (Wielkopolskie)",
    "Kuyavian-Pomeranian (Kujawsko-Pomorskie)",
    "Lesser Poland (Malopolskie)",
    "Lodz (Lodzkie)",
    "Lower Silesian (Dolnoslaskie)",
    "Lublin (Lubelskie)",
    "Lubusz (Lubuskie)",
    "Masovian (Mazowieckie)",
    "Opole (Opolskie)",
    "Podlasie (Podlaskie)",
    "Pomeranian (Pomorskie)",
    "Silesian (Slaskie)",
    "Subcarpathian (Podkarpackie)",
    "Swietokrzyskie (Swietokrzyskie)",
    "Warmian-Masurian (Warminsko-Mazurskie)",
    "West Pomeranian (Zachodniopomorskie)",
  ],
  Portugal: [
    "Aveiro",
    "Acores",
    "Beja",
    "Braga",
    "Braganca",
    "Castelo Branco",
    "Coimbra",
    "Evora",
    "Faro",
    "Guarda",
    "Leiria",
    "Lisboa",
    "Madeira",
    "Portalegre",
    "Porto",
    "Santarem",
    "Setubal",
    "Viana do Castelo",
    "Vila Real",
    "Viseu",
  ],
  "Puerto Rico": null,
  Qatar: [
    "Ad Dawhah",
    "Al Ghuwayriyah",
    "Al Jumayliyah",
    "Al Khawr",
    "Al Wakrah",
    "Ar Rayyan",
    "Jarayan al Batinah",
    "Madinat ash Shamal",
    "Umm Sa'id",
    "Umm Salal",
  ],
  "Republic of North Macedonia": null,
  Romania: [
    "Alba",
    "Arad",
    "Arges",
    "Bacau",
    "Bihor",
    "Bistrita-Nasaud",
    "Botosani",
    "Braila",
    "Brasov",
    "Bucuresti",
    "Buzau",
    "Calarasi",
    "Caras-Severin",
    "Cluj",
    "Constanta",
    "Covasna",
    "Dimbovita",
    "Dolj",
    "Galati",
    "Gorj",
    "Giurgiu",
    "Harghita",
    "Hunedoara",
    "Ialomita",
    "Iasi",
    "Ilfov",
    "Maramures",
    "Mehedinti",
    "Mures",
    "Neamt",
    "Olt",
    "Prahova",
    "Salaj",
    "Satu Mare",
    "Sibiu",
    "Suceava",
    "Teleorman",
    "Timis",
    "Tulcea",
    "Vaslui",
    "Vilcea",
    "Vrancea",
  ],
  "Russian Federation (the)": [
    "Amur",
    "Arkhangel'sk",
    "Astrakhan'",
    "Belgorod",
    "Bryansk",
    "Chelyabinsk",
    "Chita",
    "Irkutsk",
    "Ivanovo",
    "Kaliningrad",
    "Kaluga",
    "Kamchatka",
    "Kemerovo",
    "Kirov",
    "Kostroma",
    "Kurgan",
    "Kursk",
    "Leningrad",
    "Lipetsk",
    "Magadan",
    "Moscow",
    "Murmansk",
    "Nizhniy Novgorod",
    "Novgorod",
    "Novosibirsk",
    "Omsk",
    "Orenburg",
    "Orel",
    "Penza",
    "Perm'",
    "Pskov",
    "Rostov",
    "Ryazan'",
    "Sakhalin",
    "Samara",
    "Saratov",
    "Smolensk",
    "Sverdlovsk",
    "Tambov",
    "Tomsk",
    "Tula",
    "Tver'",
    "Tyumen'",
    "Ul'yanovsk",
    "Vladimir",
    "Volgograd",
    "Vologda",
    "Voronezh",
    "Yaroslavl'",
    "Adygeya",
    "Altay",
    "Bashkortostan",
    "Buryatiya",
    "Chechnya",
    "Chuvashiya",
    "Dagestan",
    "Ingushetiya",
    "Kabardino-Balkariya",
    "Kalmykiya",
    "Karachayevo-Cherkesiya",
    "Kareliya",
    "Khakasiya",
    "Komi",
    "Mariy-El",
    "Mordoviya",
    "Sakha",
    "North Ossetia",
    "Tatarstan",
    "Tyva",
    "Udmurtiya",
    "Aga Buryat",
    "Chukotka",
    "Evenk",
    "Khanty-Mansi",
    "Komi-Permyak",
    "Koryak",
    "Nenets",
    "Taymyr",
    "Ust'-Orda Buryat",
    "Yamalo-Nenets",
    "Altay",
    "Khabarovsk",
    "Krasnodar",
    "Krasnoyarsk",
    "Primorskiy",
    "Stavropol'",
    "Moscow",
    "St. Petersburg",
    "Yevrey",
  ],
  Rwanda: [
    "Butare",
    "Byumba",
    "Cyangugu",
    "Gikongoro",
    "Gisenyi",
    "Gitarama",
    "Kibungo",
    "Kibuye",
    "Kigali Rurale",
    "Kigali-ville",
    "Umutara",
    "Ruhengeri",
  ],
  Réunion: null,
  "Saint Barthélemy": null,
  "Saint Helena, Ascension and Tristan da Cunha": null,
  "Saint Kitts and Nevis": null,
  "Saint Lucia": null,
  "Saint Martin (French part)": null,
  "Saint Pierre and Miquelon": null,
  "Saint Vincent and the Grenadines": null,
  Samoa: [
    "A'ana",
    "Aiga-i-le-Tai",
    "Atua",
    "Fa'asaleleaga",
    "Gaga'emauga",
    "Gagaifomauga",
    "Palauli",
    "Satupa'itea",
    "Tuamasaga",
    "Va'a-o-Fonoti",
    "Vaisigano",
  ],
  "San Marino": [
    "Acquaviva",
    "Borgo Maggiore",
    "Chiesanuova",
    "Domagnano",
    "Faetano",
    "Fiorentino",
    "Montegiardino",
    "San Marino Citta",
    "Serravalle",
  ],
  "Sao Tome and Principe": [
    "Água Grande",
    "Cantagalo",
    "Caué",
    "Lembá",
    "Lobata",
    "Mé-Zóchi",
    "Autonomous Region of Príncipe",
  ],
  "Saudi Arabia": [
    "Al Bahah",
    "Al Hudud ash Shamaliyah",
    "Al Jawf",
    "Al Madinah",
    "Al Qasim",
    "Ar Riyad",
    "Ash Sharqiyah",
    "'Asir",
    "Ha'il",
    "Jizan",
    "Makkah",
    "Najran",
    "Tabuk",
  ],
  Senegal: [
    "Dakar",
    "Diourbel",
    "Fatick",
    "Kaolack",
    "Kolda",
    "Louga",
    "Matam",
    "Saint-Louis",
    "Tambacounda",
    "Thies",
    "Ziguinchor",
  ],
  Serbia: [
    "Valjevo",
    "Šabac",
    "Čačak",
    "Jagodina",
    "Kruševac",
    "Kraljevo",
    "Kragujevac",
    "Užice",
    "Bor",
    "Požarevac",
    "Leskovac",
    "Niš",
    "Vranje",
    "Pirot",
    "Smederevo",
    "Prokuplje",
    "Zaječar",
    "Zrenjanin",
    "Subotica",
    "Kikinda",
    "Novi Sad",
    "Pančevo",
    "Sremska Mitrovica",
    "Sombor",
  ],
  Seychelles: [
    "Anse aux Pins",
    "Anse Boileau",
    "Anse Etoile",
    "Anse Louis",
    "Anse Royale",
    "Baie Lazare",
    "Baie Sainte Anne",
    "Beau Vallon",
    "Bel Air",
    "Bel Ombre",
    "Cascade",
    "Glacis",
    "Grand' Anse",
    "Grand' Anse",
    "La Digue",
    "La Riviere Anglaise",
    "Mont Buxton",
    "Mont Fleuri",
    "Plaisance",
    "Pointe La Rue",
    "Port Glaud",
    "Saint Louis",
    "Takamaka",
  ],
  "Sierra Leone": [
    "Eastern Province",
    "Northern Province",
    "Southern Province",
    "North West Province",
    "Western Area",
  ],
  Singapore: [
    "Aljunied Group Representation Constituency",
    "Ang Mo Kio Group Representation Constituency",
    "Bishan–Toa Payoh Group Representation Constituency",
    "Chua Chu Kang Group Representation Constituency",
    "East Coast Group Representation Constituency",
    "Holland–Bukit Timah Group Representation Constituency",
    "Jalan Besar Group Representation Constituency",
    "Jurong Group Representation Constituency",
    "Marine Parade Group Representation Constituency",
    "Marsiling–Yew Tee Group Representation Constituency",
    "Nee Soon Group Representation Constituency",
    "Pasir Ris–Punggol Group Representation Constituency",
    "Sengkang Group Representation Constituency",
    "Tampines Group Representation Constituency",
    "Tanjong Pagar Group Representation Constituency",
    "West Coast Group Representation Constituency",
  ],
  "Sint Maarten (Dutch part)": null,
  Slovakia: [
    "Banskobystricky",
    "Bratislavsky",
    "Kosicky",
    "Nitriansky",
    "Presovsky",
    "Trenciansky",
    "Trnavsky",
    "Zilinsky",
  ],
  Slovenia: [
    "Ajdovscina",
    "Beltinci",
    "Benedikt",
    "Bistrica ob Sotli",
    "Bled",
    "Bloke",
    "Bohinj",
    "Borovnica",
    "Bovec",
    "Braslovce",
    "Brda",
    "Brezice",
    "Brezovica",
    "Cankova",
    "Celje",
    "Cerklje na Gorenjskem",
    "Cerknica",
    "Cerkno",
    "Cerkvenjak",
    "Crensovci",
    "Crna na Koroskem",
    "Crnomelj",
    "Destrnik",
    "Divaca",
    "Dobje",
    "Dobrepolje",
    "Dobrna",
    "Dobrova-Horjul-Polhov Gradec",
    "Dobrovnik-Dobronak",
    "Dolenjske Toplice",
    "Dol pri Ljubljani",
    "Domzale",
    "Dornava",
    "Dravograd",
    "Duplek",
    "Gorenja Vas-Poljane",
    "Gorisnica",
    "Gornja Radgona",
    "Gornji Grad",
    "Gornji Petrovci",
    "Grad",
    "Grosuplje",
    "Hajdina",
    "Hoce-Slivnica",
    "Hodos-Hodos",
    "Horjul",
    "Hrastnik",
    "Hrpelje-Kozina",
    "Idrija",
    "Ig",
    "Ilirska Bistrica",
    "Ivancna Gorica",
    "Izola-Isola",
    "Jesenice",
    "Jezersko",
    "Jursinci",
    "Kamnik",
    "Kanal",
    "Kidricevo",
    "Kobarid",
    "Kobilje",
    "Kocevje",
    "Komen",
    "Komenda",
    "Koper-Capodistria",
    "Kostel",
    "Kozje",
    "Kranj",
    "Kranjska Gora",
    "Krizevci",
    "Krsko",
    "Kungota",
    "Kuzma",
    "Lasko",
    "Lenart",
    "Lendava-Lendva",
    "Litija",
    "Ljubljana",
    "Ljubno",
    "Ljutomer",
    "Logatec",
    "Loska Dolina",
    "Loski Potok",
    "Lovrenc na Pohorju",
    "Luce",
    "Lukovica",
    "Majsperk",
    "Maribor",
    "Markovci",
    "Medvode",
    "Menges",
    "Metlika",
    "Mezica",
    "Miklavz na Dravskem Polju",
    "Miren-Kostanjevica",
    "Mirna Pec",
    "Mislinja",
    "Moravce",
    "Moravske Toplice",
    "Mozirje",
    "Murska Sobota",
    "Muta",
    "Naklo",
    "Nazarje",
    "Nova Gorica",
    "Novo Mesto",
    "Odranci",
    "Oplotnica",
    "Ormoz",
    "Osilnica",
    "Pesnica",
    "Piran-Pirano",
    "Pivka",
    "Podcetrtek",
    "Podlehnik",
    "Podvelka",
    "Polzela",
    "Postojna",
    "Prebold",
    "Preddvor",
    "Prevalje",
    "Ptuj",
    "Puconci",
    "Race-Fram",
    "Radece",
    "Radenci",
    "Radlje ob Dravi",
    "Radovljica",
    "Ravne na Koroskem",
    "Razkrizje",
    "Ribnica",
    "Ribnica na Pohorju",
    "Rogasovci",
    "Rogaska Slatina",
    "Rogatec",
    "Ruse",
    "Salovci",
    "Selnica ob Dravi",
    "Semic",
    "Sempeter-Vrtojba",
    "Sencur",
    "Sentilj",
    "Sentjernej",
    "Sentjur pri Celju",
    "Sevnica",
    "Sezana",
    "Skocjan",
    "Skofja Loka",
    "Skofljica",
    "Slovenj Gradec",
    "Slovenska Bistrica",
    "Slovenske Konjice",
    "Smarje pri Jelsah",
    "Smartno ob Paki",
    "Smartno pri Litiji",
    "Sodrazica",
    "Solcava",
    "Sostanj",
    "Starse",
    "Store",
    "Sveta Ana",
    "Sveti Andraz v Slovenskih Goricah",
    "Sveti Jurij",
    "Tabor",
    "Tisina",
    "Tolmin",
    "Trbovlje",
    "Trebnje",
    "Trnovska Vas",
    "Trzic",
    "Trzin",
    "Turnisce",
    "Velenje",
    "Velika Polana",
    "Velike Lasce",
    "Verzej",
    "Videm",
    "Vipava",
    "Vitanje",
    "Vodice",
    "Vojnik",
    "Vransko",
    "Vrhnika",
    "Vuzenica",
    "Zagorje ob Savi",
    "Zalec",
    "Zavrc",
    "Zelezniki",
    "Zetale",
    "Ziri",
    "Zirovnica",
    "Zuzemberk",
    "Zrece",
  ],
  "Solomon Islands": [
    "Central",
    "Choiseul",
    "Guadalcanal",
    "Honiara",
    "Isabel",
    "Makira",
    "Malaita",
    "Rennell and Bellona",
    "Temotu",
    "Western",
  ],
  Somalia: [
    "Awdal",
    "Bakool",
    "Banaadir",
    "Bari",
    "Bay",
    "Galguduud",
    "Gedo",
    "Hiiraan",
    "Jubbada Dhexe",
    "Jubbada Hoose",
    "Mudug",
    "Nugaal",
    "Sanaag",
    "Shabeellaha Dhexe",
    "Shabeellaha Hoose",
    "Sool",
    "Togdheer",
    "Woqooyi Galbeed",
  ],
  "South Africa": [
    "Eastern Cape",
    "Free State",
    "Gauteng",
    "KwaZulu-Natal",
    "Limpopo",
    "Mpumalanga",
    "North-West",
    "Northern Cape",
    "Western Cape",
  ],
  "South Georgia and the South Sandwich Islands": null,
  "South Sudan": null,
  Spain: [
    "Andalucia",
    "Aragon",
    "Asturias",
    "Baleares",
    "Ceuta",
    "Canarias",
    "Cantabria",
    "Castilla-La Mancha",
    "Castilla y Leon",
    "Cataluna",
    "Comunidad Valenciana",
    "Extremadura",
    "Galicia",
    "La Rioja",
    "Madrid",
    "Melilla",
    "Murcia",
    "Navarra",
    "Pais Vasco",
  ],
  "Sri Lanka": [
    "Central",
    "North Central",
    "North Eastern",
    "North Western",
    "Sabaragamuwa",
    "Southern",
    "Uva",
    "Western",
  ],
  "Sudan (the)": [
    "A'ali an Nil",
    "Al Bahr al Ahmar",
    "Al Buhayrat",
    "Al Jazirah",
    "Al Khartum",
    "Al Qadarif",
    "Al Wahdah",
    "An Nil al Abyad",
    "An Nil al Azraq",
    "Ash Shamaliyah",
    "Bahr al Jabal",
    "Gharb al Istiwa'iyah",
    "Gharb Bahr al Ghazal",
    "Gharb Darfur",
    "Gharb Kurdufan",
    "Janub Darfur",
    "Janub Kurdufan",
    "Junqali",
    "Kassala",
    "Nahr an Nil",
    "Shamal Bahr al Ghazal",
    "Shamal Darfur",
    "Shamal Kurdufan",
    "Sharq al Istiwa'iyah",
    "Sinnar",
    "Warab",
  ],
  Suriname: [
    "Brokopondo",
    "Commewijne",
    "Coronie",
    "Marowijne",
    "Nickerie",
    "Para",
    "Paramaribo",
    "Saramacca",
    "Sipaliwini",
    "Wanica",
  ],
  "Svalbard and Jan Mayen": null,
  Swaziland: ["Hhohho", "Lubombo", "Manzini", "Shiselweni"],
  Sweden: [
    "Blekinge",
    "Dalarna",
    "Gävleborg",
    "Gotland",
    "Halland",
    "Jämtland",
    "Jönköping",
    "Kalmar",
    "Kronoberg",
    "Norrbotten",
    "Örebro",
    "Östergötland",
    "Skåne",
    "Södermanland",
    "Stockholm",
    "Uppsala",
    "Värmland",
    "Västerbotten",
    "Västernorrland",
    "Västmanland",
    "Västra Götaland",
  ],
  Switzerland: [
    "Aargau",
    "Appenzell Ausser-Rhoden",
    "Appenzell Inner-Rhoden",
    "Basel-Landschaft",
    "Basel-Stadt",
    "Bern",
    "Fribourg",
    "Geneve",
    "Glarus",
    "Graubunden",
    "Jura",
    "Luzern",
    "Neuchatel",
    "Nidwalden",
    "Obwalden",
    "Sankt Gallen",
    "Schaffhausen",
    "Schwyz",
    "Solothurn",
    "Thurgau",
    "Ticino",
    "Uri",
    "Valais",
    "Vaud",
    "Zug",
    "Zurich",
  ],
  "Syrian Arab Republic": [
    "Al Hasakah",
    "Al Ladhiqiyah",
    "Al Qunaytirah",
    "Ar Raqqah",
    "As Suwayda'",
    "Dar'a",
    "Dayr az Zawr",
    "Dimashq",
    "Halab",
    "Hamah",
    "Hims",
    "Idlib",
    "Rif Dimashq",
    "Tartus",
  ],
  Taiwan: [
    "Chang-hua",
    "Chia-i",
    "Hsin-chu",
    "Hua-lien",
    "I-lan",
    "Kao-hsiung",
    "Kin-men",
    "Lien-chiang",
    "Miao-li",
    "Nan-t'ou",
    "P'eng-hu",
    "P'ing-tung",
    "T'ai-chung",
    "T'ai-nan",
    "T'ai-pei",
    "T'ai-tung",
    "T'ao-yuan",
    "Yun-lin",
    "Chia-i",
    "Chi-lung",
    "Hsin-chu",
    "T'ai-chung",
    "T'ai-nan",
    "Kao-hsiung city",
    "T'ai-pei city",
  ],
  Tajikistan: null,
  "Tanzania, United Republic of": [
    "Arusha",
    "Dar es Salaam",
    "Dodoma",
    "Districts of Republican Subordination",
    "Dushanbe",
    "Gorno-Badakhshan Autonomous Region",
    "Iringa",
    "Kagera",
    "Khatlon Region",
    "Kigoma",
    "Kilimanjaro",
    "Lindi",
    "Manyara",
    "Mara",
    "Mbeya",
    "Morogoro",
    "Mtwara",
    "Mwanza",
    "Pemba North",
    "Pemba South",
    "Pwani",
    "Rukwa",
    "Ruvuma",
    "Shinyanga",
    "Singida",
    "Sughd Region",
    "Tabora",
    "Tanga",
    "Zanzibar Central/South",
    "Zanzibar North",
    "Zanzibar Urban/West",
  ],
  Thailand: [
    "Amnat Charoen",
    "Ang Thong",
    "Buriram",
    "Chachoengsao",
    "Chai Nat",
    "Chaiyaphum",
    "Chanthaburi",
    "Chiang Mai",
    "Chiang Rai",
    "Chon Buri",
    "Chumphon",
    "Kalasin",
    "Kamphaeng Phet",
    "Kanchanaburi",
    "Khon Kaen",
    "Krabi",
    "Krung Thep Mahanakhon",
    "Lampang",
    "Lamphun",
    "Loei",
    "Lop Buri",
    "Mae Hong Son",
    "Maha Sarakham",
    "Mukdahan",
    "Nakhon Nayok",
    "Nakhon Pathom",
    "Nakhon Phanom",
    "Nakhon Ratchasima",
    "Nakhon Sawan",
    "Nakhon Si Thammarat",
    "Nan",
    "Narathiwat",
    "Nong Bua Lamphu",
    "Nong Khai",
    "Nonthaburi",
    "Pathum Thani",
    "Pattani",
    "Phangnga",
    "Phatthalung",
    "Phayao",
    "Phetchabun",
    "Phetchaburi",
    "Phichit",
    "Phitsanulok",
    "Phra Nakhon Si Ayutthaya",
    "Phrae",
    "Phuket",
    "Prachin Buri",
    "Prachuap Khiri Khan",
    "Ranong",
    "Ratchaburi",
    "Rayong",
    "Roi Et",
    "Sa Kaeo",
    "Sakon Nakhon",
    "Samut Prakan",
    "Samut Sakhon",
    "Samut Songkhram",
    "Sara Buri",
    "Satun",
    "Sing Buri",
    "Sisaket",
    "Songkhla",
    "Sukhothai",
    "Suphan Buri",
    "Surat Thani",
    "Surin",
    "Tak",
    "Trang",
    "Trat",
    "Ubon Ratchathani",
    "Udon Thani",
    "Uthai Thani",
    "Uttaradit",
    "Yala",
    "Yasothon",
  ],
  "Timor-Leste": null,
  Togo: ["Kara", "Plateaux", "Savanes", "Centrale", "Maritime"],
  Tokelau: null,
  Tonga: ["Tongatapu", "Vavaʻu", "Haʻapai", "ʻEua", "Ongo Niua", "Tonga"],
  "Trinidad and Tobago": [
    "Couva",
    "Diego Martin",
    "Mayaro",
    "Penal",
    "Princes Town",
    "Sangre Grande",
    "San Juan",
    "Siparia",
    "Tunapuna",
    "Port-of-Spain",
    "San Fernando",
    "Arima",
    "Point Fortin",
    "Chaguanas",
    "Tobago",
  ],
  Tunisia: [
    "Ariana (Aryanah)",
    "Beja (Bajah)",
    "Ben Arous (Bin 'Arus)",
    "Bizerte (Banzart)",
    "Gabes (Qabis)",
    "Gafsa (Qafsah)",
    "Jendouba (Jundubah)",
    "Kairouan (Al Qayrawan)",
    "Kasserine (Al Qasrayn)",
    "Kebili (Qibili)",
    "Kef (Al Kaf)",
    "Mahdia (Al Mahdiyah)",
    "Manouba (Manubah)",
    "Medenine (Madanin)",
    "Monastir (Al Munastir)",
    "Nabeul (Nabul)",
    "Sfax (Safaqis)",
    "Sidi Bou Zid (Sidi Bu Zayd)",
    "Siliana (Silyanah)",
    "Sousse (Susah)",
    "Tataouine (Tatawin)",
    "Tozeur (Tawzar)",
    "Tunis",
    "Zaghouan (Zaghwan)",
  ],
  Turkey: [
    "Adana",
    "Adiyaman",
    "Afyonkarahisar",
    "Agri",
    "Aksaray",
    "Amasya",
    "Ankara",
    "Antalya",
    "Ardahan",
    "Artvin",
    "Aydin",
    "Balikesir",
    "Bartin",
    "Batman",
    "Bayburt",
    "Bilecik",
    "Bingol",
    "Bitlis",
    "Bolu",
    "Burdur",
    "Bursa",
    "Canakkale",
    "Cankiri",
    "Corum",
    "Denizli",
    "Diyarbakir",
    "Duzce",
    "Edirne",
    "Elazig",
    "Erzincan",
    "Erzurum",
    "Eskisehir",
    "Gaziantep",
    "Giresun",
    "Gumushane",
    "Hakkari",
    "Hatay",
    "Igdir",
    "Isparta",
    "Istanbul",
    "Izmir",
    "Kahramanmaras",
    "Karabuk",
    "Karaman",
    "Kars",
    "Kastamonu",
    "Kayseri",
    "Kilis",
    "Kirikkale",
    "Kirklareli",
    "Kirsehir",
    "Kocaeli",
    "Konya",
    "Kutahya",
    "Malatya",
    "Manisa",
    "Mardin",
    "Mersin",
    "Mugla",
    "Mus",
    "Nevsehir",
    "Nigde",
    "Ordu",
    "Osmaniye",
    "Rize",
    "Sakarya",
    "Samsun",
    "Sanliurfa",
    "Siirt",
    "Sinop",
    "Sirnak",
    "Sivas",
    "Tekirdag",
    "Tokat",
    "Trabzon",
    "Tunceli",
    "Usak",
    "Van",
    "Yalova",
    "Yozgat",
    "Zonguldak",
  ],
  Turkmenistan: [
    "Ahal Welayaty (Ashgabat)",
    "Balkan Welayaty (Balkanabat)",
    "Dashoguz Welayaty",
    "Lebap Welayaty (Turkmenabat)",
    "Mary Welayaty",
  ],
  "Turks and Caicos Islands (the)": null,
  Tuvalu: null,
  Uganda: [
    "Adjumani",
    "Apac",
    "Arua",
    "Bugiri",
    "Bundibugyo",
    "Bushenyi",
    "Busia",
    "Gulu",
    "Hoima",
    "Iganga",
    "Jinja",
    "Kabale",
    "Kabarole",
    "Kaberamaido",
    "Kalangala",
    "Kampala",
    "Kamuli",
    "Kamwenge",
    "Kanungu",
    "Kapchorwa",
    "Kasese",
    "Katakwi",
    "Kayunga",
    "Kibale",
    "Kiboga",
    "Kisoro",
    "Kitgum",
    "Kotido",
    "Kumi",
    "Kyenjojo",
    "Lira",
    "Luwero",
    "Masaka",
    "Masindi",
    "Mayuge",
    "Mbale",
    "Mbarara",
    "Moroto",
    "Moyo",
    "Mpigi",
    "Mubende",
    "Mukono",
    "Nakapiripirit",
    "Nakasongola",
    "Nebbi",
    "Ntungamo",
    "Pader",
    "Pallisa",
    "Rakai",
    "Rukungiri",
    "Sembabule",
    "Sironko",
    "Soroti",
    "Tororo",
    "Wakiso",
    "Yumbe",
  ],
  Ukraine: [
    "Cherkasy",
    "Chernihiv",
    "Chernivtsi",
    "Crimea",
    "Dnipropetrovs'k",
    "Donets'k",
    "Ivano-Frankivs'k",
    "Kharkiv",
    "Kherson",
    "Khmel'nyts'kyy",
    "Kirovohrad",
    "Kiev",
    "Kyyiv",
    "Luhans'k",
    "L'viv",
    "Mykolayiv",
    "Odesa",
    "Poltava",
    "Rivne",
    "Sevastopol'",
    "Sumy",
    "Ternopil'",
    "Vinnytsya",
    "Volyn'",
    "Zakarpattya",
    "Zaporizhzhya",
    "Zhytomyr",
  ],
  "United Arab Emirates (the)": [
    "Abu Dhabi",
    "'Ajman",
    "Al Fujayrah",
    "Sharjah",
    "Dubai",
    "Ra's al Khaymah",
    "Umm al Qaywayn",
  ],
  "United Kingdom of Great Britain and Northern Ireland (the)": [
    "Aberconwy and Colwyn",
    "Aberdeen City",
    "Aberdeenshire",
    "Anglesey",
    "Angus",
    "Antrim",
    "Argyll and Bute",
    "Armagh",
    "Avon",
    "Ayrshire",
    "Bath and NE Somerset",
    "Bedfordshire",
    "Belfast",
    "Berkshire",
    "Berwickshire",
    "BFPO",
    "Blaenau Gwent",
    "Buckinghamshire",
    "Caernarfonshire",
    "Caerphilly",
    "Caithness",
    "Cambridgeshire",
    "Cardiff",
    "Cardiganshire",
    "Carmarthenshire",
    "Ceredigion",
    "Channel Islands",
    "Cheshire",
    "City of Bristol",
    "Clackmannanshire",
    "Clwyd",
    "Conwy",
    "Cornwall/Scilly",
    "Cumbria",
    "Denbighshire",
    "Derbyshire",
    "Derry/Londonderry",
    "Devon",
    "Dorset",
    "Down",
    "Dumfries and Galloway",
    "Dunbartonshire",
    "Dundee",
    "Durham",
    "Dyfed",
    "East Ayrshire",
    "East Dunbartonshire",
    "East Lothian",
    "East Renfrewshire",
    "East Riding Yorkshire",
    "East Sussex",
    "Edinburgh",
    "England",
    "Essex",
    "Falkirk",
    "Fermanagh",
    "Fife",
    "Flintshire",
    "Glasgow",
    "Gloucestershire",
    "Greater London",
    "Greater Manchester",
    "Gwent",
    "Gwynedd",
    "Hampshire",
    "Hartlepool",
    "Hereford and Worcester",
    "Hertfordshire",
    "Highlands",
    "Inverclyde",
    "Inverness-Shire",
    "Isle of Man",
    "Isle of Wight",
    "Kent",
    "Kincardinshire",
    "Kingston Upon Hull",
    "Kinross-Shire",
    "Kirklees",
    "Lanarkshire",
    "Lancashire",
    "Leicestershire",
    "Lincolnshire",
    "Londonderry",
    "Merseyside",
    "Merthyr Tydfil",
    "Mid Glamorgan",
    "Mid Lothian",
    "Middlesex",
    "Monmouthshire",
    "Moray",
    "Neath & Port Talbot",
    "Newport",
    "Norfolk",
    "North Ayrshire",
    "North East Lincolnshire",
    "North Lanarkshire",
    "North Lincolnshire",
    "North Somerset",
    "North Yorkshire",
    "Northamptonshire",
    "Northern Ireland",
    "Northumberland",
    "Nottinghamshire",
    "Orkney and Shetland Isles",
    "Oxfordshire",
    "Pembrokeshire",
    "Perth and Kinross",
    "Powys",
    "Redcar and Cleveland",
    "Renfrewshire",
    "Rhonda Cynon Taff",
    "Rutland",
    "Scottish Borders",
    "Shetland",
    "Shropshire",
    "Somerset",
    "South Ayrshire",
    "South Glamorgan",
    "South Gloucesteshire",
    "South Lanarkshire",
    "South Yorkshire",
    "Staffordshire",
    "Stirling",
    "Stockton On Tees",
    "Suffolk",
    "Surrey",
    "Swansea",
    "Torfaen",
    "Tyne and Wear",
    "Tyrone",
    "Vale Of Glamorgan",
    "Wales",
    "Warwickshire",
    "West Berkshire",
    "West Dunbartonshire",
    "West Glamorgan",
    "West Lothian",
    "West Midlands",
    "West Sussex",
    "West Yorkshire",
    "Western Isles",
    "Wiltshire",
    "Wirral",
    "Worcestershire",
    "Wrexham",
    "York",
  ],
  "United States Minor Outlying Islands (the)": null,
  "United States of America (the)": [
    "Alabama",
    "Alaska",
    "Arizona",
    "Arkansas",
    "California",
    "Colorado",
    "Connecticut",
    "Delaware",
    "District of Columbia",
    "Florida",
    "Georgia",
    "Hawaii",
    "Idaho",
    "Illinois",
    "Indiana",
    "Iowa",
    "Kansas",
    "Kentucky",
    "Louisiana",
    "Maine",
    "Maryland",
    "Massachusetts",
    "Michigan",
    "Minnesota",
    "Mississippi",
    "Missouri",
    "Montana",
    "Nebraska",
    "Nevada",
    "New Hampshire",
    "New Jersey",
    "New Mexico",
    "New York",
    "North Carolina",
    "North Dakota",
    "Ohio",
    "Oklahoma",
    "Oregon",
    "Pennsylvania",
    "Rhode Island",
    "South Carolina",
    "South Dakota",
    "Tennessee",
    "Texas",
    "Utah",
    "Vermont",
    "Virginia",
    "Washington",
    "West Virginia",
    "Wisconsin",
    "Wyoming",
  ],
  Uruguay: [
    "Artigas",
    "Canelones",
    "Cerro Largo",
    "Colonia",
    "Durazno",
    "Flores",
    "Florida",
    "Lavalleja",
    "Maldonado",
    "Montevideo",
    "Paysandu",
    "Rio Negro",
    "Rivera",
    "Rocha",
    "Salto",
    "San Jose",
    "Soriano",
    "Tacuarembo",
    "Treinta y Tres",
  ],
  Uzbekistan: [
    "Andijon Viloyati",
    "Buxoro Viloyati",
    "Farg'ona Viloyati",
    "Jizzax Viloyati",
    "Namangan Viloyati",
    "Navoiy Viloyati",
    "Qashqadaryo Viloyati",
    "Qaraqalpog'iston Respublikasi",
    "Samarqand Viloyati",
    "Sirdaryo Viloyati",
    "Surxondaryo Viloyati",
    "Toshkent Shahri",
    "Toshkent Viloyati",
    "Xorazm Viloyati",
  ],
  Vanuatu: ["Malampa", "Penama", "Sanma", "Shefa", "Tafea", "Torba"],
  "Venezuela (Bolivarian Republic of)": [
    "Amazonas",
    "Anzoategui",
    "Apure",
    "Aragua",
    "Barinas",
    "Bolivar",
    "Carabobo",
    "Cojedes",
    "Delta Amacuro",
    "Dependencias Federales",
    "Distrito Federal",
    "Falcon",
    "Guarico",
    "Lara",
    "Merida",
    "Miranda",
    "Monagas",
    "Nueva Esparta",
    "Portuguesa",
    "Sucre",
    "Tachira",
    "Trujillo",
    "Vargas",
    "Yaracuy",
    "Zulia",
  ],
  "Viet Nam": [
    "An Giang",
    "Bac Giang",
    "Bac Kan",
    "Bac Lieu",
    "Bac Ninh",
    "Ba Ria-Vung Tau",
    "Ben Tre",
    "Binh Dinh",
    "Binh Duong",
    "Binh Phuoc",
    "Binh Thuan",
    "Ca Mau",
    "Cao Bang",
    "Dac Lak",
    "Dac Nong",
    "Dien Bien",
    "Dong Nai",
    "Dong Thap",
    "Gia Lai",
    "Ha Giang",
    "Hai Duong",
    "Ha Nam",
    "Ha Tay",
    "Ha Tinh",
    "Hau Giang",
    "Hoa Binh",
    "Hung Yen",
    "Khanh Hoa",
    "Kien Giang",
    "Kon Tum",
    "Lai Chau",
    "Lam Dong",
    "Lang Son",
    "Lao Cai",
    "Long An",
    "Nam Dinh",
    "Nghe An",
    "Ninh Binh",
    "Ninh Thuan",
    "Phu Tho",
    "Phu Yen",
    "Quang Binh",
    "Quang Nam",
    "Quang Ngai",
    "Quang Ninh",
    "Quang Tri",
    "Soc Trang",
    "Son La",
    "Tay Ninh",
    "Thai Binh",
    "Thai Nguyen",
    "Thanh Hoa",
    "Thua Thien-Hue",
    "Tien Giang",
    "Tra Vinh",
    "Tuyen Quang",
    "Vinh Long",
    "Vinh Phuc",
    "Yen Bai",
    "Can Tho",
    "Da Nang",
    "Hai Phong",
    "Hanoi",
    "Ho Chi Minh",
  ],
  "Virgin Islands (British)": null,
  "Virgin Islands (U.S.)": null,
  "Wallis and Futuna": null,
  "Western Sahara": null,
  Yemen: [
    "Abyan",
    "'Adan",
    "Ad Dali'",
    "Al Bayda'",
    "Al Hudaydah",
    "Al Jawf",
    "Al Mahrah",
    "Al Mahwit",
    "'Amran",
    "Dhamar",
    "Hadramawt",
    "Hajjah",
    "Ibb",
    "Lahij",
    "Ma'rib",
    "Sa'dah",
    "San'a'",
    "Shabwah",
    "Ta'izz",
  ],
  Zambia: [
    "Central",
    "Copperbelt",
    "Eastern",
    "Luapula",
    "Lusaka",
    "Northern",
    "North-Western",
    "Southern",
    "Western",
  ],
  Zimbabwe: [
    "Bulawayo",
    "Harare",
    "Manicaland",
    "Mashonaland Central",
    "Mashonaland East",
    "Mashonaland West",
    "Masvingo",
    "Matabeleland North",
    "Matabeleland South",
    "Midlands",
  ],
  "Åland Islands": null,
};

// Notification Icons
export const notificationIcons = {
  default: <IoIosNotifications className="text-lg" />,
};

export const colors = {
  error: "border-red-600 bg-red-100 text-red-600",
  info: "border-blue-600 bg-blue-100 text-blue-600",
  warning: "border-yellow-600 bg-yellow-100 text-yellow-600",
  success: "border-green-600 bg-green-100 text-green-600",
};

export const paginationEntries = ["All", 50, 100, 200, 500, 1000];
